DATABASE_ADDRESS: localhost
DATABASE_PORT: 55001
DATABASE_NAME: wqp_db
SCHEMA_NAME: wqp
SCHEMA_NAME_DBUNIT: wqp
SCHEMA_OWNER_USERNAME: wqp_core
SCHEMA_OWNER_PASSWORD: changeMe
READ_ONLY_USERNAME: wqp_user
READ_ONLY_PASSWORD: changeMe
WSL_SCHEMA_NAME_DBUNIT: wqp
WSL_SCHEMA_OWNER_USERNAME: wqp_core
WSL_SCHEMA_OWNER_PASSWORD: changeMe
MAX_RESULT_ROWS: 20000000
