spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_ADDRESS}:${DATABASE_PORT}/${DATABASE_NAME}?currentSchema=${SCHEMA_NAME}
    username: ${READ_ONLY_USERNAME}
    password: ${READ_ONLY_PASSWORD}
    hikari:
      auto-commit: false

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}
  error:
    include-stacktrace: never

springdoc:
  version: "@project.version@"

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    javax.management.mbeanserver: OFF
    mybatis: DEBUG
    result: DEBUG
    resultBroad: DEBUG
    resultPhysChem: DEBUG
    resultPrimary: DEBUG
    dynamicWhere: DEBUG
    pcResult: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
site:
  url:
    base: ${SITE_URL_BASE}
  swagger:
    apiDocsUrl: ${SERVER_CONTEXT_PATH}/v3/api-docs
    deployName: ${DEPLOY_NAME}

codes:
  url: ${CODES_SERVICE_URL}
  mimeType: json
  timeout:
    milli: ${CODES_TIMEOUT_MILLI}

nldi:
  timeout:
    milli: ${NLDI_TIMEOUT_MILLI}

kml:
  style:
    url: ${KML_STYLE_URL}
max:
  result:
    rows: ${MAX_RESULT_ROWS}

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: /about
      exposure:
        include:
        - info
        - health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: never
