package gov.usgs.cida.wqp.mapping;

import java.math.BigDecimal;
import java.util.LinkedHashMap;
import java.util.Map;

import static gov.usgs.cida.wqp.mapping.ActivityColumn.*;
import static gov.usgs.cida.wqp.mapping.StationColumn.*;
import static gov.usgs.cida.wqp.swagger.model.StationCountJson.*;

public class TestSummaryMonitoringLocationMap {

	public static final Map<String, Object> SUMMARY_MONITORING_LOCATION_ONE_YEAR;
	static {
		SUMMARY_MONITORING_LOCATION_ONE_YEAR = new LinkedHashMap<>();
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_DATA_SOURCE, STORET);
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_SITE_ID, "organization-siteId");
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_ORGANIZATION, "organization");
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_ORGANIZATION_NAME, "organization name");
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_SITE_TYPE, "siteType");
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_HUC_8, "00000000");
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_MONITORING_LOCATION_TYPE, "River/Stream");
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_LATITUDE, "43.3330000");
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_LONGITUDE, "-89.8989000");
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_ACTIVITY_COUNT, BigDecimal.valueOf(1));
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_RESULT_COUNT, BigDecimal.valueOf(1));
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_MONITORING_LOCATION_SUMMARY, "{\"characteristicType\": 1}");	
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_STATE_NAME, "Hawaii");
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_COUNTY_NAME, "Clay County");
		SUMMARY_MONITORING_LOCATION_ONE_YEAR.put(KEY_STATION_NAME, "Wintergreen ln");
	}
	
	public static final Map<String, Object> SUMMARY_MONITORING_LOCATION_FIVE_YEARS;
	static {
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS = new LinkedHashMap<>();
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_DATA_SOURCE, STORET);
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_SITE_ID, "organization-siteId");
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_ORGANIZATION, "organization");
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_ORGANIZATION_NAME, "organization name");
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_SITE_TYPE, "siteType");
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_HUC_8, "00000000");
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_MONITORING_LOCATION_TYPE, "River/Stream");
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_LATITUDE, "43.3330000");
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_LONGITUDE, "-89.8989000");
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_ACTIVITY_COUNT, BigDecimal.valueOf(3));
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_RESULT_COUNT, BigDecimal.valueOf(3));
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_MONITORING_LOCATION_SUMMARY, "{\"characteristicType\": 3}");	
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_STATE_NAME, "Hawaii");
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_COUNTY_NAME, "Clay County");
		SUMMARY_MONITORING_LOCATION_FIVE_YEARS.put(KEY_STATION_NAME, "Wintergreen ln");
	}
	
	public static final Map<String, Object> SUMMARY_MONITORING_LOCATION_ALL_YEARS;
	static {
		SUMMARY_MONITORING_LOCATION_ALL_YEARS = new LinkedHashMap<>();
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_DATA_SOURCE, STORET);
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_SITE_ID, "organization-siteId");
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_ORGANIZATION, "organization");
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_ORGANIZATION_NAME, "organization name");
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_SITE_TYPE, "siteType");
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_HUC_8, "00000000");
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_MONITORING_LOCATION_TYPE, "River/Stream");
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_LATITUDE, "43.3330000");
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_LONGITUDE, "-89.8989000");
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_ACTIVITY_COUNT, BigDecimal.valueOf(4));
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_RESULT_COUNT, BigDecimal.valueOf(4));
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_MONITORING_LOCATION_SUMMARY, "{\"characteristicType\": 4}");	
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_STATE_NAME, "Hawaii");
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_COUNTY_NAME, "Clay County");
		SUMMARY_MONITORING_LOCATION_ALL_YEARS.put(KEY_STATION_NAME, "Wintergreen ln");
	}

	private TestSummaryMonitoringLocationMap() {
	}
}
