package gov.usgs.cida.wqp.mapping;

import static gov.usgs.cida.wqp.mapping.BaseColumn.DATA_SOURCE;
import static gov.usgs.cida.wqp.mapping.BaseColumn.ORGANIZATION;
import static gov.usgs.cida.wqp.mapping.BaseColumn.ORGANIZATION_NAME;
import static gov.usgs.cida.wqp.mapping.BaseColumn.SITE_ID;
import static gov.usgs.cida.wqp.mapping.StationColumn.CHARACTERISTIC_NAME;
import static gov.usgs.cida.wqp.mapping.StationColumn.CHARACTERISTIC_TYPE;
import static gov.usgs.cida.wqp.mapping.StationColumn.COUNTY_NAME;
import static gov.usgs.cida.wqp.mapping.StationColumn.HUC_8;
import static gov.usgs.cida.wqp.mapping.StationColumn.LAST_RESULT_DATE;
import static gov.usgs.cida.wqp.mapping.StationColumn.LATITUDE;
import static gov.usgs.cida.wqp.mapping.StationColumn.LONGITUDE;
import static gov.usgs.cida.wqp.mapping.StationColumn.MONITORING_LOCATION_TYPE;
import static gov.usgs.cida.wqp.mapping.StationColumn.MONITORING_LOCATION_TYPE_NAME;
import static gov.usgs.cida.wqp.mapping.StationColumn.MONITORING_LOCATION_URL;
import static gov.usgs.cida.wqp.mapping.StationColumn.SITE_TYPE;
import static gov.usgs.cida.wqp.mapping.StationColumn.STATE_NAME;
import static gov.usgs.cida.wqp.mapping.StationColumn.STATION_ID;
import static gov.usgs.cida.wqp.mapping.StationColumn.STATION_NAME;
import static gov.usgs.cida.wqp.mapping.StationColumn.THE_YEAR;
import static gov.usgs.cida.wqp.mapping.StationColumn.TOTAL_ACTIVITIES;
import static gov.usgs.cida.wqp.mapping.StationColumn.TOTAL_RESULTS;
import static gov.usgs.cida.wqp.mapping.delimited.BaseDelimited.VALUE_MONITORING_LOCATION_IDENTIFIER;
import static gov.usgs.cida.wqp.mapping.delimited.BaseDelimited.VALUE_ORGANIZATION_FORMAL_NAME;
import static gov.usgs.cida.wqp.mapping.delimited.BaseDelimited.VALUE_ORGANIZATION_IDENTIFIER;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.MAPPINGS;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_CHARACTERISTIC_NAME;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_CHARACTERISTIC_TYPE;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_COUNTY_NAME;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_DATA_SOURCE_PROVIDER;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_HUC_8;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_LAST_RESULT_DATE;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_MONITORING_LOCATION_LATITUDE;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_MONITORING_LOCATION_LONGITUDE;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_MONITORING_LOCATION_NAME;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_MONITORING_LOCATION_TYPE;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_MONITORING_LOCATION_TYPE_NAME;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_MONITORING_LOCATION_URL;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_RESOLVED_MONITORING_LOCATION;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_STATE_NAME;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_STATION_ID;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_THE_YEAR;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_TOTAL_ACTIVITIES;
import static gov.usgs.cida.wqp.mapping.delimited.PeriodOfRecordDelimited.VALUE_TOTAL_RESULTS;
import java.util.LinkedHashMap;
import java.util.Map;

public class TestPeriodOfRecordCSVMap {	
	
	// next section is for monitoring location STEWARDS_36
	// for sorted tests-should only appear in 'all' year summary
	public static final Map<String, Object> STEWARDS_36_2000;	
	static {
		STEWARDS_36_2000 = new LinkedHashMap<>();
		STEWARDS_36_2000.put(DATA_SOURCE, VALUE_DATA_SOURCE_PROVIDER);
		STEWARDS_36_2000.put(STATION_ID, VALUE_STATION_ID);
		STEWARDS_36_2000.put(THE_YEAR, VALUE_THE_YEAR);
		STEWARDS_36_2000.put(CHARACTERISTIC_TYPE, VALUE_CHARACTERISTIC_TYPE);
		STEWARDS_36_2000.put(CHARACTERISTIC_NAME, VALUE_CHARACTERISTIC_NAME);
		STEWARDS_36_2000.put(TOTAL_ACTIVITIES, VALUE_TOTAL_ACTIVITIES);
		STEWARDS_36_2000.put(TOTAL_RESULTS, VALUE_TOTAL_RESULTS);
		STEWARDS_36_2000.put(LAST_RESULT_DATE, VALUE_LAST_RESULT_DATE);	
		STEWARDS_36_2000.put(ORGANIZATION, VALUE_ORGANIZATION_IDENTIFIER);
		STEWARDS_36_2000.put(ORGANIZATION_NAME, VALUE_ORGANIZATION_FORMAL_NAME);		
		STEWARDS_36_2000.put(SITE_ID, VALUE_MONITORING_LOCATION_IDENTIFIER);
		STEWARDS_36_2000.put(MONITORING_LOCATION_TYPE, VALUE_MONITORING_LOCATION_TYPE);
		STEWARDS_36_2000.put(STATION_NAME, VALUE_MONITORING_LOCATION_NAME);
		STEWARDS_36_2000.put(MONITORING_LOCATION_TYPE_NAME, VALUE_MONITORING_LOCATION_TYPE_NAME);
		STEWARDS_36_2000.put(SITE_TYPE, VALUE_RESOLVED_MONITORING_LOCATION);
		STEWARDS_36_2000.put(HUC_8, VALUE_HUC_8);
		STEWARDS_36_2000.put(MONITORING_LOCATION_URL, VALUE_MONITORING_LOCATION_URL);
		STEWARDS_36_2000.put(COUNTY_NAME, VALUE_COUNTY_NAME);
		STEWARDS_36_2000.put(STATE_NAME, VALUE_STATE_NAME);
		STEWARDS_36_2000.put(LATITUDE, VALUE_MONITORING_LOCATION_LATITUDE);
		STEWARDS_36_2000.put(LONGITUDE, VALUE_MONITORING_LOCATION_LONGITUDE);		
	}
	
	// next section is for monitoring location STORET_504707
	// for sorted tests-should only appear in 'all' year summary
	public static final Map<String, Object> STORET_504707_1910;	
	static {
		STORET_504707_1910 = new LinkedHashMap<>();	
				MAPPINGS.put(DATA_SOURCE, VALUE_DATA_SOURCE_PROVIDER);
		STORET_504707_1910.put(STATION_ID, VALUE_STATION_ID);
		STORET_504707_1910.put(THE_YEAR, VALUE_THE_YEAR);
		STORET_504707_1910.put(CHARACTERISTIC_TYPE, VALUE_CHARACTERISTIC_TYPE);
		STORET_504707_1910.put(CHARACTERISTIC_NAME, VALUE_CHARACTERISTIC_NAME);
		STORET_504707_1910.put(TOTAL_ACTIVITIES, VALUE_TOTAL_ACTIVITIES);
		STORET_504707_1910.put(TOTAL_RESULTS, VALUE_TOTAL_RESULTS);
		STORET_504707_1910.put(LAST_RESULT_DATE, VALUE_LAST_RESULT_DATE);	
		STORET_504707_1910.put(ORGANIZATION, VALUE_ORGANIZATION_IDENTIFIER);
		STORET_504707_1910.put(ORGANIZATION_NAME, VALUE_ORGANIZATION_FORMAL_NAME);		
		STORET_504707_1910.put(SITE_ID, VALUE_MONITORING_LOCATION_IDENTIFIER);
		STORET_504707_1910.put(MONITORING_LOCATION_TYPE, VALUE_MONITORING_LOCATION_TYPE);
		STORET_504707_1910.put(STATION_NAME, VALUE_MONITORING_LOCATION_NAME);
		STORET_504707_1910.put(MONITORING_LOCATION_TYPE_NAME, VALUE_MONITORING_LOCATION_TYPE_NAME);
		STORET_504707_1910.put(SITE_TYPE, VALUE_RESOLVED_MONITORING_LOCATION);
		STORET_504707_1910.put(HUC_8, VALUE_HUC_8);
		STORET_504707_1910.put(MONITORING_LOCATION_URL, VALUE_MONITORING_LOCATION_URL);
		STORET_504707_1910.put(COUNTY_NAME, VALUE_COUNTY_NAME);
		STORET_504707_1910.put(STATE_NAME, VALUE_STATE_NAME);
		STORET_504707_1910.put(LATITUDE, VALUE_MONITORING_LOCATION_LATITUDE);
		STORET_504707_1910.put(LONGITUDE, VALUE_MONITORING_LOCATION_LONGITUDE);
	}		
	
	// next section is for monitoring location NWIS_1353690
	// for sorted tests-should only appear in 'all' year summary
	public static final Map<String, Object> NWIS_1353690_2010;	
	static {
		NWIS_1353690_2010 = new LinkedHashMap<>();
		NWIS_1353690_2010.put(DATA_SOURCE, VALUE_DATA_SOURCE_PROVIDER);
		NWIS_1353690_2010.put(STATION_ID, VALUE_STATION_ID);
		NWIS_1353690_2010.put(THE_YEAR, VALUE_THE_YEAR);
		NWIS_1353690_2010.put(CHARACTERISTIC_TYPE, VALUE_CHARACTERISTIC_TYPE);
		NWIS_1353690_2010.put(CHARACTERISTIC_NAME, VALUE_CHARACTERISTIC_NAME);
		NWIS_1353690_2010.put(TOTAL_ACTIVITIES, VALUE_TOTAL_ACTIVITIES);
		NWIS_1353690_2010.put(TOTAL_RESULTS, VALUE_TOTAL_RESULTS);
		NWIS_1353690_2010.put(LAST_RESULT_DATE, VALUE_LAST_RESULT_DATE);	
		NWIS_1353690_2010.put(ORGANIZATION, VALUE_ORGANIZATION_IDENTIFIER);
		NWIS_1353690_2010.put(ORGANIZATION_NAME, VALUE_ORGANIZATION_FORMAL_NAME);		
		NWIS_1353690_2010.put(SITE_ID, VALUE_MONITORING_LOCATION_IDENTIFIER);
		NWIS_1353690_2010.put(MONITORING_LOCATION_TYPE, VALUE_MONITORING_LOCATION_TYPE);
		NWIS_1353690_2010.put(STATION_NAME, VALUE_MONITORING_LOCATION_NAME);
		NWIS_1353690_2010.put(MONITORING_LOCATION_TYPE_NAME, VALUE_MONITORING_LOCATION_TYPE_NAME);
		NWIS_1353690_2010.put(SITE_TYPE, VALUE_RESOLVED_MONITORING_LOCATION);
		NWIS_1353690_2010.put(HUC_8, VALUE_HUC_8);
		NWIS_1353690_2010.put(MONITORING_LOCATION_URL, VALUE_MONITORING_LOCATION_URL);
		NWIS_1353690_2010.put(COUNTY_NAME, VALUE_COUNTY_NAME);
		NWIS_1353690_2010.put(STATE_NAME, VALUE_STATE_NAME);
		NWIS_1353690_2010.put(LATITUDE, VALUE_MONITORING_LOCATION_LATITUDE);
		NWIS_1353690_2010.put(LONGITUDE, VALUE_MONITORING_LOCATION_LONGITUDE);		
	}
	
	// for sorted tests, monitoring location 1353690 should only appear in 5, and all year summary
	public static final Map<String, Object> NWIS_1353690_2017;	
	static {
		NWIS_1353690_2017 = new LinkedHashMap<>();
				MAPPINGS.put(DATA_SOURCE, VALUE_DATA_SOURCE_PROVIDER);
		NWIS_1353690_2017.put(STATION_ID, VALUE_STATION_ID);
		NWIS_1353690_2017.put(THE_YEAR, VALUE_THE_YEAR);
		NWIS_1353690_2017.put(CHARACTERISTIC_TYPE, VALUE_CHARACTERISTIC_TYPE);
		NWIS_1353690_2017.put(CHARACTERISTIC_NAME, VALUE_CHARACTERISTIC_NAME);
		NWIS_1353690_2017.put(TOTAL_ACTIVITIES, VALUE_TOTAL_ACTIVITIES);
		NWIS_1353690_2017.put(TOTAL_RESULTS, VALUE_TOTAL_RESULTS);
		NWIS_1353690_2017.put(LAST_RESULT_DATE, VALUE_LAST_RESULT_DATE);	
		NWIS_1353690_2017.put(ORGANIZATION, VALUE_ORGANIZATION_IDENTIFIER);
		NWIS_1353690_2017.put(ORGANIZATION_NAME, VALUE_ORGANIZATION_FORMAL_NAME);		
		NWIS_1353690_2017.put(SITE_ID, VALUE_MONITORING_LOCATION_IDENTIFIER);
		NWIS_1353690_2017.put(MONITORING_LOCATION_TYPE, VALUE_MONITORING_LOCATION_TYPE);
		NWIS_1353690_2017.put(STATION_NAME, VALUE_MONITORING_LOCATION_NAME);
		NWIS_1353690_2017.put(MONITORING_LOCATION_TYPE_NAME, VALUE_MONITORING_LOCATION_TYPE_NAME);
		NWIS_1353690_2017.put(SITE_TYPE, VALUE_RESOLVED_MONITORING_LOCATION);
		NWIS_1353690_2017.put(HUC_8, VALUE_HUC_8);
		NWIS_1353690_2017.put(MONITORING_LOCATION_URL, VALUE_MONITORING_LOCATION_URL);
		NWIS_1353690_2017.put(COUNTY_NAME, VALUE_COUNTY_NAME);
		NWIS_1353690_2017.put(STATE_NAME, VALUE_STATE_NAME);
		NWIS_1353690_2017.put(LATITUDE, VALUE_MONITORING_LOCATION_LATITUDE);
		NWIS_1353690_2017.put(LONGITUDE, VALUE_MONITORING_LOCATION_LONGITUDE);
		
	}
	// for sorted tests-monitoring location 1353690 should appear every summary
	public static final Map<String, Object> NWIS_1353690_2018;	
	static {
		NWIS_1353690_2018 = new LinkedHashMap<>();
				MAPPINGS.put(DATA_SOURCE, VALUE_DATA_SOURCE_PROVIDER);
		NWIS_1353690_2018.put(STATION_ID, VALUE_STATION_ID);
		NWIS_1353690_2018.put(THE_YEAR, VALUE_THE_YEAR);
		NWIS_1353690_2018.put(CHARACTERISTIC_TYPE, VALUE_CHARACTERISTIC_TYPE);
		NWIS_1353690_2018.put(CHARACTERISTIC_NAME, VALUE_CHARACTERISTIC_NAME);
		NWIS_1353690_2018.put(TOTAL_ACTIVITIES, VALUE_TOTAL_ACTIVITIES);
		NWIS_1353690_2018.put(TOTAL_RESULTS, VALUE_TOTAL_RESULTS);
		NWIS_1353690_2018.put(LAST_RESULT_DATE, VALUE_LAST_RESULT_DATE);	
		NWIS_1353690_2018.put(ORGANIZATION, VALUE_ORGANIZATION_IDENTIFIER);
		NWIS_1353690_2018.put(ORGANIZATION_NAME, VALUE_ORGANIZATION_FORMAL_NAME);		
		NWIS_1353690_2018.put(SITE_ID, VALUE_MONITORING_LOCATION_IDENTIFIER);
		NWIS_1353690_2018.put(MONITORING_LOCATION_TYPE, VALUE_MONITORING_LOCATION_TYPE);
		NWIS_1353690_2018.put(STATION_NAME, VALUE_MONITORING_LOCATION_NAME);
		NWIS_1353690_2018.put(MONITORING_LOCATION_TYPE_NAME, VALUE_MONITORING_LOCATION_TYPE_NAME);
		NWIS_1353690_2018.put(SITE_TYPE, VALUE_RESOLVED_MONITORING_LOCATION);
		NWIS_1353690_2018.put(HUC_8, VALUE_HUC_8);
		NWIS_1353690_2018.put(MONITORING_LOCATION_URL, VALUE_MONITORING_LOCATION_URL);
		NWIS_1353690_2018.put(COUNTY_NAME, VALUE_COUNTY_NAME);
		NWIS_1353690_2018.put(STATE_NAME, VALUE_STATE_NAME);
		NWIS_1353690_2018.put(LATITUDE, VALUE_MONITORING_LOCATION_LATITUDE);
		NWIS_1353690_2018.put(LONGITUDE, VALUE_MONITORING_LOCATION_LONGITUDE);
		
	}
	
	// next section is for monitoring location NWIS_1360035 (different from NWIS_1353690)
	// for sorted tests-monitoring location 1360035 should only appear in 5, and all year summary
	public static final Map<String, Object> NWIS_1360035_2017;	
	static {
		NWIS_1360035_2017 = new LinkedHashMap<>();
				MAPPINGS.put(DATA_SOURCE, VALUE_DATA_SOURCE_PROVIDER);
		NWIS_1360035_2017.put(STATION_ID, VALUE_STATION_ID);
		NWIS_1360035_2017.put(THE_YEAR, VALUE_THE_YEAR);
		NWIS_1360035_2017.put(CHARACTERISTIC_TYPE, VALUE_CHARACTERISTIC_TYPE);
		NWIS_1360035_2017.put(CHARACTERISTIC_NAME, VALUE_CHARACTERISTIC_NAME);
		NWIS_1360035_2017.put(TOTAL_ACTIVITIES, VALUE_TOTAL_ACTIVITIES);
		NWIS_1360035_2017.put(TOTAL_RESULTS, VALUE_TOTAL_RESULTS);
		NWIS_1360035_2017.put(LAST_RESULT_DATE, VALUE_LAST_RESULT_DATE);	
		NWIS_1360035_2017.put(ORGANIZATION, VALUE_ORGANIZATION_IDENTIFIER);
		NWIS_1360035_2017.put(ORGANIZATION_NAME, VALUE_ORGANIZATION_FORMAL_NAME);		
		NWIS_1360035_2017.put(SITE_ID, VALUE_MONITORING_LOCATION_IDENTIFIER);
		NWIS_1360035_2017.put(MONITORING_LOCATION_TYPE, VALUE_MONITORING_LOCATION_TYPE);
		NWIS_1360035_2017.put(STATION_NAME, VALUE_MONITORING_LOCATION_NAME);
		NWIS_1360035_2017.put(MONITORING_LOCATION_TYPE_NAME, VALUE_MONITORING_LOCATION_TYPE_NAME);
		NWIS_1360035_2017.put(SITE_TYPE, VALUE_RESOLVED_MONITORING_LOCATION);
		NWIS_1360035_2017.put(HUC_8, VALUE_HUC_8);
		NWIS_1360035_2017.put(MONITORING_LOCATION_URL, VALUE_MONITORING_LOCATION_URL);
		NWIS_1360035_2017.put(COUNTY_NAME, VALUE_COUNTY_NAME);
		NWIS_1360035_2017.put(STATE_NAME, VALUE_STATE_NAME);
		NWIS_1360035_2017.put(LATITUDE, VALUE_MONITORING_LOCATION_LATITUDE);
		NWIS_1360035_2017.put(LONGITUDE, VALUE_MONITORING_LOCATION_LONGITUDE);
		
	}
	// for sorted tests-monitoring location 1360035 should appear every summary
	public static final Map<String, Object> NWIS_1360035_2018;	
	static {
		NWIS_1360035_2018 = new LinkedHashMap<>();
		NWIS_1360035_2018.put(DATA_SOURCE, VALUE_DATA_SOURCE_PROVIDER);
		NWIS_1360035_2018.put(STATION_ID, VALUE_STATION_ID);
		NWIS_1360035_2018.put(THE_YEAR, VALUE_THE_YEAR);
		NWIS_1360035_2018.put(CHARACTERISTIC_TYPE, VALUE_CHARACTERISTIC_TYPE);
		NWIS_1360035_2018.put(CHARACTERISTIC_NAME, VALUE_CHARACTERISTIC_NAME);
		NWIS_1360035_2018.put(TOTAL_ACTIVITIES, VALUE_TOTAL_ACTIVITIES);
		NWIS_1360035_2018.put(TOTAL_RESULTS, VALUE_TOTAL_RESULTS);
		NWIS_1360035_2018.put(LAST_RESULT_DATE, VALUE_LAST_RESULT_DATE);	
		NWIS_1360035_2018.put(ORGANIZATION, VALUE_ORGANIZATION_IDENTIFIER);
		NWIS_1360035_2018.put(ORGANIZATION_NAME, VALUE_ORGANIZATION_FORMAL_NAME);		
		NWIS_1360035_2018.put(SITE_ID, VALUE_MONITORING_LOCATION_IDENTIFIER);
		NWIS_1360035_2018.put(MONITORING_LOCATION_TYPE, VALUE_MONITORING_LOCATION_TYPE);
		NWIS_1360035_2018.put(STATION_NAME, VALUE_MONITORING_LOCATION_NAME);
		NWIS_1360035_2018.put(MONITORING_LOCATION_TYPE_NAME, VALUE_MONITORING_LOCATION_TYPE_NAME);
		NWIS_1360035_2018.put(SITE_TYPE, VALUE_RESOLVED_MONITORING_LOCATION);
		NWIS_1360035_2018.put(HUC_8, VALUE_HUC_8);
		NWIS_1360035_2018.put(MONITORING_LOCATION_URL, VALUE_MONITORING_LOCATION_URL);
		NWIS_1360035_2018.put(COUNTY_NAME, VALUE_COUNTY_NAME);
		NWIS_1360035_2018.put(STATE_NAME, VALUE_STATE_NAME);
		NWIS_1360035_2018.put(LATITUDE, VALUE_MONITORING_LOCATION_LATITUDE);
		NWIS_1360035_2018.put(LONGITUDE, VALUE_MONITORING_LOCATION_LONGITUDE);
		
	}		
	
	
	
		MAPPINGS.put(DATA_SOURCE, VALUE_DATA_SOURCE_PROVIDER);
		MAPPINGS.put(STATION_ID, VALUE_STATION_ID);
		MAPPINGS.put(THE_YEAR, VALUE_THE_YEAR);
		MAPPINGS.put(CHARACTERISTIC_TYPE, VALUE_CHARACTERISTIC_TYPE);
		MAPPINGS.put(CHARACTERISTIC_NAME, VALUE_CHARACTERISTIC_NAME);
		MAPPINGS.put(TOTAL_ACTIVITIES, VALUE_TOTAL_ACTIVITIES);
		MAPPINGS.put(TOTAL_RESULTS, VALUE_TOTAL_RESULTS);
		MAPPINGS.put(LAST_RESULT_DATE, VALUE_LAST_RESULT_DATE);	
		MAPPINGS.put(ORGANIZATION, VALUE_ORGANIZATION_IDENTIFIER);
		MAPPINGS.put(ORGANIZATION_NAME, VALUE_ORGANIZATION_FORMAL_NAME);		
		MAPPINGS.put(SITE_ID, VALUE_MONITORING_LOCATION_IDENTIFIER);
		MAPPINGS.put(MONITORING_LOCATION_TYPE, VALUE_MONITORING_LOCATION_TYPE);
		MAPPINGS.put(STATION_NAME, VALUE_MONITORING_LOCATION_NAME);
		MAPPINGS.put(MONITORING_LOCATION_TYPE_NAME, VALUE_MONITORING_LOCATION_TYPE_NAME);
		MAPPINGS.put(SITE_TYPE, VALUE_RESOLVED_MONITORING_LOCATION);
		MAPPINGS.put(HUC_8, VALUE_HUC_8);
		MAPPINGS.put(MONITORING_LOCATION_URL, VALUE_MONITORING_LOCATION_URL);
		MAPPINGS.put(COUNTY_NAME, VALUE_COUNTY_NAME);
		MAPPINGS.put(STATE_NAME, VALUE_STATE_NAME);
		MAPPINGS.put(LATITUDE, VALUE_MONITORING_LOCATION_LATITUDE);
		MAPPINGS.put(LONGITUDE, VALUE_MONITORING_LOCATION_LONGITUDE);

	
	public static final Map<String, Object> PERIOD_OF_RECORD_ONE_YEAR;	
	static {
		PERIOD_OF_RECORD_ONE_YEAR = new LinkedHashMap<>();
		// following appear in 1, 5, and all years
		PERIOD_OF_RECORD_ONE_YEAR.put("sampleRecord_1", NWIS_1360035_2018);
		PERIOD_OF_RECORD_ONE_YEAR.put("sampleRecord_2", NWIS_1353690_2018);		
	}
	
	public static final Map<String, Object> PERIOD_OF_RECORD_FIVE_YEAR;	
	static {
		PERIOD_OF_RECORD_FIVE_YEAR = new LinkedHashMap<>();
		// following appear in 1, 5, and all years
		PERIOD_OF_RECORD_FIVE_YEAR.put("sampleRecord_1", NWIS_1360035_2018);
		PERIOD_OF_RECORD_FIVE_YEAR.put("sampleRecord_2", NWIS_1353690_2018);
		// following appear in 5 and all years
		PERIOD_OF_RECORD_FIVE_YEAR.put("sampleRecord_3", NWIS_1360035_2017);
		PERIOD_OF_RECORD_FIVE_YEAR.put("sampleRecord_4", NWIS_1353690_2017);		
	}
	
	public static final Map<String, Object> PERIOD_OF_RECORD_ALL_YEARS;	
	static {
		PERIOD_OF_RECORD_ALL_YEARS = new LinkedHashMap<>();
		// following appear in 1, 5, and all years
		PERIOD_OF_RECORD_ALL_YEARS.put("sampleRecord_1", NWIS_1360035_2018);
		PERIOD_OF_RECORD_ALL_YEARS.put("sampleRecord_2", NWIS_1353690_2018);
		// following appear in 5 and all years
		PERIOD_OF_RECORD_ALL_YEARS.put("sampleRecord_3", NWIS_1360035_2017);
		PERIOD_OF_RECORD_ALL_YEARS.put("sampleRecord_4", NWIS_1353690_2017);
		// following only appear in all years
		PERIOD_OF_RECORD_ALL_YEARS.put("sampleRecord_5", STEWARDS_36_2000);
		PERIOD_OF_RECORD_ALL_YEARS.put("sampleRecord_6", STORET_504707_1910);
		PERIOD_OF_RECORD_ALL_YEARS.put("sampleRecord_7", NWIS_1353690_2010);
	}
	
	private TestPeriodOfRecordCSVMap() {
	}
}
