package gov.usgs.cida.wqp.mapping;

import static gov.usgs.cida.wqp.mapping.OrganizationColumn.*;
import static gov.usgs.cida.wqp.swagger.model.StationCountJson.STORET;

import java.math.BigDecimal;
import java.util.LinkedHashMap;
import java.util.Map;

public class TestOrganizationMap {

	public static final Map<String, Object> ORGANIZATION;
	static {
		ORGANIZATION = new LinkedHashMap<String, Object>();
		ORGANIZATION.put(KEY_DATA_SOURCE_ID, BigDecimal.valueOf(3));
		ORGANIZATION.put(KEY_DATA_SOURCE, STORET);
		ORGANIZATION.put(KEY_ORGANIZATION, "ORGANIZATION");
		ORGANIZATION.put(KEY_ORGANIZATION_NAME, "ORGANIZATION_NAME");
		ORGANIZATION.put(KEY_ORGANIZATION_ID, "ORGANIZATION_ID");
		ORGANIZATION.put(KEY_ORGANIZATION_DESCRIPTION, "ORGANIZATION_DESCRIPTION");
		ORGANIZATION.put(KEY_TRIBAL_CODE, "TRIBAL_CODE");
		ORGANIZATION.put(KEY_ELECTRONIC_ADDRESS, "ELECTRONIC_ADDRESS");
		ORGANIZATION.put(KEY_TELEPHONIC, "TELEPHONIC");
		ORGANIZATION.put(KEY_ADDRESS_TYPE_1, "ADDRESS_TYPE_1");
		ORGANIZATION.put(KEY_ADDRESS_TEXT_1, "ADDRESS_TEXT_1");
		ORGANIZATION.put(KEY_SUPPLEMENTAL_ADDRESS_TEXT_1, "SUPPLEMENTAL_ADDRESS_TEXT_1");
		ORGANIZATION.put(KEY_LOCALITY_NAME_1, "LOCALITY_NAME_1");
		ORGANIZATION.put(KEY_POSTAL_CODE_1, "POSTAL_CODE_1");
		ORGANIZATION.put(KEY_COUNTRY_CODE_1, "COUNTRY_CODE_1");
		ORGANIZATION.put(KEY_STATE_CODE_1, "STATE_CODE_1");
		ORGANIZATION.put(KEY_COUNTY_CODE_1, "COUNTY_CODE_1");
		ORGANIZATION.put(KEY_ADDRESS_TYPE_2, "ADDRESS_TYPE_2");
		ORGANIZATION.put(KEY_ADDRESS_TEXT_2, "ADDRESS_TEXT_2");
		ORGANIZATION.put(KEY_SUPPLEMENTAL_ADDRESS_TEXT_2, "SUPPLEMENTAL_ADDRESS_TEXT_2");
		ORGANIZATION.put(KEY_LOCALITY_NAME_2, "LOCALITY_NAME_2");
		ORGANIZATION.put(KEY_POSTAL_CODE_2, "POSTAL_CODE_2");
		ORGANIZATION.put(KEY_COUNTRY_CODE_2, "COUNTRY_CODE_2");
		ORGANIZATION.put(KEY_STATE_CODE_2, "STATE_CODE_2");
		ORGANIZATION.put(KEY_COUNTY_CODE_2, "COUNTY_CODE_2");
		ORGANIZATION.put(KEY_ADDRESS_TYPE_3, "ADDRESS_TYPE_3");
		ORGANIZATION.put(KEY_ADDRESS_TEXT_3, "ADDRESS_TEXT_3");
		ORGANIZATION.put(KEY_SUPPLEMENTAL_ADDRESS_TEXT_3, "SUPPLEMENTAL_ADDRESS_TEXT_3");
		ORGANIZATION.put(KEY_LOCALITY_NAME_3, "LOCALITY_NAME_3");
		ORGANIZATION.put(KEY_POSTAL_CODE_3, "POSTAL_CODE_3");
		ORGANIZATION.put(KEY_COUNTRY_CODE_3, "COUNTRY_CODE_3");
		ORGANIZATION.put(KEY_STATE_CODE_3, "STATE_CODE_3");
		ORGANIZATION.put(KEY_COUNTY_CODE_3, "COUNTY_CODE_3");
	}

	private TestOrganizationMap() {
	}
}
