package gov.usgs.cida.wqp.mapping;

import java.math.BigDecimal;
import java.util.LinkedHashMap;
import java.util.Map;

import static gov.usgs.cida.wqp.mapping.ProjectColumn.*;
import static gov.usgs.cida.wqp.mapping.ProjectMonitoringLocationWeightingColumn.*;

public class TestProjectMLWeightingMap {

	public static final Map<String, Object> PROJECT_MONITORING_LOCATION_WEIGHTING;
	static {
		PROJECT_MONITORING_LOCATION_WEIGHTING = new LinkedHashMap<String, Object>();
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_DATA_SOURCE_ID, BigDecimal.valueOf(3));
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_ORGANIZATION, "test-org");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_ORGANIZATION_NAME, "test-org-name");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_PROJECT_IDENTIFIER, "YZ123");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_SITE_ID, "SITE-321");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_PRJMLW_VALUE, 52);
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_PRJMLW_UNIT, "km");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_PRJMLW_STATISTICAL_STRATUM, "123");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_PRJMLW_LOCATION_CATEGORY, "test");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_PRJMLW_LOCATION_STATUS, "good");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_PRJMLW_REFERENCE_LOCATION_TYPE_CODE, "12");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_PRJMLW_REFERENCE_LOCATION_START_DATE, "11-11-2011");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_PRJMLW_REFERENCE_LOCATION_END_DATE, "11-11-2011");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_REFERENCE_LOCATION_CITATION_TITLE, "test-title");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_REFERENCE_LOCATION_CITATION_CREATOR, "test-creator");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_REFERENCE_LOCATION_CITATION_SUBJECT, "test-subject");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_REFERENCE_LOCATION_CITATION_PUBLISHER, "test-publisher");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_REFERENCE_LOCATION_CITATION_DATE, "test-cite-date");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_REFERENCE_LOCATION_CITATION_IDENTIFIER, "test-cite-id");
		PROJECT_MONITORING_LOCATION_WEIGHTING.put(KEY_PRJMLW_COMMENT, "comment");
	}

	private TestProjectMLWeightingMap() {
	}
}
