package gov.usgs.cida.wqp.mapping;

import java.util.LinkedHashMap;
import java.util.Map;

public class BioResultColumn extends ResultColumn {

	public static final Map<String, String> mappings;
		
	static {
		mappings = new LinkedHashMap<String,String>();
		mappings.put(KEY_ORGANIZATION, VALUE_ORGANIZATION_IDENTIFIER);
		mappings.put(KEY_ORGANIZATION_NAME, VALUE_ORGANIZATION_FORMAL_NAME);
		mappings.put(KEY_ACTIVITY, VALUE_ACTIVITY);
		mappings.put(KEY_ACTIVITY_TYPE_CODE, VALUE_ACTIVITY_TYPE_CODE);
		mappings.put(KEY_SAMPLE_MEDIA, VALUE_SAMPLE_MEDIA);
		mappings.put(KEY_ACTIVITY_MEDIA_SUBDIV_NAME, VALUE_ACTIVITY_MEDIA_SUBDIV_NAME);
		mappings.put(KEY_EVENT_DATE, VALUE_EVENT_DATE);
		mappings.put(KEY_ACTIVITY_START_TIME, VALUE_ACTIVITY_START_TIME);
		mappings.put(KEY_ACT_START_TIME_ZONE, VALUE_ACT_START_TIME_ZONE);
		mappings.put(KEY_ACTIVITY_STOP_DATE, VALUE_ACTIVITY_STOP_DATE);
		mappings.put(KEY_ACTIVITY_STOP_TIME, VALUE_ACTIVITY_STOP_TIME);
		mappings.put(KEY_ACT_STOP_TIME_ZONE, VALUE_ACT_STOP_TIME_ZONE);
		mappings.put(KEY_ACTIVITY_RELATIVE_DEPTH, VALUE_ACTIVITY_RELATIVE_DEPTH);//
		mappings.put(KEY_ACTIVITY_DEPTH, VALUE_ACTIVITY_DEPTH);
		mappings.put(KEY_ACTIVITY_DEPTH_UNIT, VALUE_ACTIVITY_DEPTH_UNIT);
		mappings.put(KEY_ACTIVITY_DEPTH_REF_POINT, VALUE_ACTIVITY_DEPTH_REF_POINT);
		mappings.put(KEY_ACTIVITY_UPPER_DEPTH, VALUE_ACTIVITY_UPPER_DEPTH);
		mappings.put(KEY_ACTIVITY_UPPER_DEPTH_UNIT, VALUE_ACTIVITY_UPPER_DEPTH_UNIT);
		mappings.put(KEY_ACTIVITY_LOWER_DEPTH, VALUE_ACTIVITY_LOWER_DEPTH);
		mappings.put(KEY_ACTIVITY_LOWER_DEPTH_UNIT, VALUE_ACTIVITY_LOWER_DEPTH_UNIT);
		mappings.put(KEY_PROJECT_ID, VALUE_PROJECT_ID);
		mappings.put(KEY_ACTIVITY_CONDUCTING_ORG, VALUE_ACTIVITY_CONDUCTING_ORG);
		mappings.put(KEY_SITE_ID, VALUE_MONITORING_LOCATION_IDENTIFIER);
		mappings.put(KEY_ACTIVITY_COMMENT, VALUE_ACTIVITY_COMMENT);
		mappings.put(KEY_SAMPLE_AQFR_NAME, VALUE_SAMPLE_AQFR_NAME);
		mappings.put(KEY_HYDROLOGIC_CONDITION_NAME, VALUE_HYDROLOGIC_CONDITION_NAME);
		mappings.put(KEY_HYDROLOGIC_EVENT_NAME, VALUE_HYDROLOGIC_EVENT_NAME);
		
		
		mappings.put(KEY_ACTIVITY_LATITUDE, VALUE_ACTIVITY_LATITUDE);//
		mappings.put(KEY_ACTIVITY_LONGITUDE, VALUE_ACTIVITY_LONGITUDE);//
		mappings.put(KEY_ACTIVITY_SOURCE_MAP_SCALE, VALUE_ACTIVITY_SOURCE_MAP_SCALE);//
		mappings.put(KEY_ACT_HORIZONTAL_ACCURACY, VALUE_ACT_HORIZONTAL_ACCURACY);//
		mappings.put(KEY_ACT_HORIZONTAL_ACCURACY_UNIT, VALUE_ACT_HORIZONTAL_ACCURACY_UNIT);//
		mappings.put(KEY_ACT_HORIZONTAL_COLLECT_METHOD, VALUE_ACT_HORIZONTAL_COLLECT_METHOD);//
		mappings.put(KEY_ACT_HORIZONTAL_DATUM_NAME, VALUE_ACT_HORIZONTAL_DATUM_NAME);//
		mappings.put(KEY_ASSEMBLAGE_SAMPLED_NAME, VALUE_ASSEMBLAGE_SAMPLED_NAME);//
		mappings.put(KEY_ACT_COLLECTION_DURATION, VALUE_ACT_COLLECTION_DURATION);//
		mappings.put(KEY_ACT_COLLECTION_DURATION_UNIT, VALUE_ACT_COLLECTION_DURATION_UNIT);//
		mappings.put(KEY_ACT_SAM_COMPNT_NAME, VALUE_ACT_SAM_COMPNT_NAME);//
		mappings.put(KEY_ACT_SAM_COMPNT_PLACE_IN_SERIES, VALUE_ACT_SAM_COMPNT_PLACE_IN_SERIES);//
		mappings.put(KEY_ACT_REACH_LENGTH, VALUE_ACT_REACH_LENGTH);//
		mappings.put(KEY_ACT_REACH_LENGTH_UNIT, VALUE_ACT_REACH_LENGTH_UNIT);//
		mappings.put(KEY_ACT_REACH_WIDTH, VALUE_ACT_REACH_WIDTH);//
		mappings.put(KEY_ACT_REACH_WIDTH_UNIT, VALUE_ACT_REACH_WIDTH_UNIT);//
		mappings.put(KEY_ACT_PASS_COUNT, VALUE_ACT_PASS_COUNT);//
		mappings.put(KEY_NET_TYPE_NAME, VALUE_NET_TYPE_NAME);//
		mappings.put(KEY_ACT_NET_SURFACE_AREA, VALUE_ACT_NET_SURFACE_AREA);//
		mappings.put(KEY_ACT_NET_SURFACE_AREA_UNIT, VALUE_ACT_NET_SURFACE_AREA_UNIT);//
		mappings.put(KEY_ACT_NET_MESH_SIZE, VALUE_ACT_NET_MESH_SIZE);//
		mappings.put(KEY_ACT_NET_MESH_SIZE_UNIT, VALUE_ACT_NET_MESH_SIZE_UNIT);//
		mappings.put(KEY_ACT_BOAT_SPEED, VALUE_ACT_BOAT_SPEED);//
		mappings.put(KEY_ACT_BOAT_SPEED_UNIT, VALUE_ACT_BOAT_SPEED_UNIT);//
		mappings.put(KEY_ACT_CURRENT_SPEED, VALUE_ACT_CURRENT_SPEED);//
		mappings.put(KEY_ACT_CURRENT_SPEED_UNIT, VALUE_ACT_CURRENT_SPEED_UNIT);//
		mappings.put(KEY_TOXICITY_TEST_TYPE_NAME, VALUE_TOXICITY_TEST_TYPE_NAME);//
		
		
		mappings.put(KEY_SAMPLE_COLLECT_METHOD_ID, VALUE_SAMPLE_COLLECT_METHOD_ID);
		mappings.put(KEY_SAMPLE_COLLECT_METHOD_CTX, VALUE_SAMPLE_COLLECT_METHOD_CTX);
		mappings.put(KEY_SAMPLE_COLLECT_METHOD_NAME, VALUE_SAMPLE_COLLECT_METHOD_NAME);
		
		
		mappings.put(KEY_ACT_SAM_COLLECT_METH_QUAL_TYPE, VALUE_ACT_SAM_COLLECT_METH_QUAL_TYPE);//
		mappings.put(KEY_ACT_SAM_COLLECT_METH_DESC, VALUE_ACT_SAM_COLLECT_METH_DESC);//
		
		
		mappings.put(KEY_SAMPLE_COLLECT_EQUIP_NAME, VALUE_SAMPLE_COLLECT_EQUIP_NAME);
		
		
		mappings.put(KEY_ACT_SAM_COLLECT_EQUIP_COMMENTS, VALUE_ACT_SAM_COLLECT_EQUIP_COMMENTS);//
		mappings.put(KEY_ACT_SAM_PREP_METH_ID, VALUE_ACT_SAM_PREP_METH_ID);//
		mappings.put(KEY_ACT_SAM_PREP_METH_CONTEXT, VALUE_ACT_SAM_PREP_METH_CONTEXT);//
		mappings.put(KEY_ACT_SAM_PREP_METH_NAME, VALUE_ACT_SAM_PREP_METH_NAME);//
		mappings.put(KEY_ACT_SAM_PREP_METH_QUAL_TYPE, VALUE_ACT_SAM_PREP_METH_QUAL_TYPE);//
		mappings.put(KEY_ACT_SAM_PREP_METH_DESC, VALUE_ACT_SAM_PREP_METH_DESC);//
		mappings.put(KEY_SAMPLE_CONTAINER_TYPE, VALUE_SAMPLE_CONTAINER_TYPE);//
		mappings.put(KEY_SAMPLE_CONTAINER_COLOR, VALUE_SAMPLE_CONTAINER_COLOR);//
		mappings.put(KEY_ACT_SAM_CHEMICAL_PRESERVATIVE, VALUE_ACT_SAM_CHEMICAL_PRESERVATIVE);//
		mappings.put(KEY_THERMAL_PRESERVATIVE_NAME, VALUE_THERMAL_PRESERVATIVE_NAME);//
		mappings.put(KEY_ACT_SAM_TRANSPORT_STORAGE_DESC, VALUE_ACT_SAM_TRANSPORT_STORAGE_DESC);//
		mappings.put(KEY_METRIC_TYPE_IDENTIFIER, VALUE_METRIC_TYPE_IDENTIFIER);//
		mappings.put(KEY_METRIC_TYPE_CONTEXT, VALUE_METRIC_TYPE_CONTEXT);//
		mappings.put(KEY_METRIC_TYPE_NAME, VALUE_METRIC_TYPE_NAME);//
		mappings.put(KEY_METRIC_CITATION_TITLE, VALUE_METRIC_CITATION_TITLE);//
		mappings.put(KEY_METRIC_CITATION_CREATOR, VALUE_METRIC_CITATION_CREATOR);//
		mappings.put(KEY_METRIC_CITATION_SUBJECT, VALUE_METRIC_CITATION_SUBJECT);//
		mappings.put(KEY_METRIC_CITATION_PUBLISHER, VALUE_METRIC_CITATION_PUBLISHER);//
		mappings.put(KEY_METRIC_CITATION_DATE, VALUE_METRIC_CITATION_DATE);//
		mappings.put(KEY_METRIC_CITATION_ID, VALUE_METRIC_CITATION_ID);//
		mappings.put(KEY_METRIC_TYPE_SCALE, VALUE_METRIC_TYPE_SCALE);//
		mappings.put(KEY_FORMULA_DESCRIPTION, VALUE_FORMULA_DESCRIPTION);//
		mappings.put(KEY_ACTIVITY_METRIC_VALUE, VALUE_ACTIVITY_METRIC_VALUE);//
		mappings.put(KEY_ACTIVITY_METRIC_UNIT, VALUE_ACTIVITY_METRIC_UNIT);//
		mappings.put(KEY_ACTIVITY_METRIC_SCORE, VALUE_ACTIVITY_METRIC_SCORE);//
		mappings.put(KEY_ACTIVITY_METRIC_COMMENT, VALUE_ACTIVITY_METRIC_COMMENT);//
		mappings.put(KEY_INDEX_IDENTIFIER, VALUE_INDEX_IDENTIFIER);//
		mappings.put(KEY_RES_DATA_LOGGER_LINE, VALUE_RES_DATA_LOGGER_LINE);//

		
		mappings.put(KEY_RESULT_DETECTION_CONDITION_TX, VALUE_RESULT_DETECTION_CONDITION_TX);
		
		
		mappings.put(KEY_METHOD_SPECIFICATION_NAME, VALUE_METHOD_SPECIFICATION_NAME);//
		
		
		mappings.put(KEY_CHARACTERISTIC_NAME, VALUE_CHARACTERISTIC_NAME);
		mappings.put(KEY_SAMPLE_FRACTION_TYPE, VALUE_SAMPLE_FRACTION_TYPE);
		mappings.put(KEY_RESULT_MEASURE_VALUE, VALUE_RESULT_MEASURE_VALUE);
		mappings.put(KEY_RESULT_UNIT, VALUE_RESULT_UNIT);
		mappings.put(KEY_RESULT_MEAS_QUAL_CODE, VALUE_RESULT_MEAS_QUAL_CODE);
		mappings.put(KEY_RESULT_VALUE_STATUS, VALUE_RESULT_VALUE_STATUS);
		mappings.put(KEY_STATISTIC_TYPE, VALUE_STATISTIC_TYPE);
		mappings.put(KEY_RESULT_VALUE_TYPE, VALUE_RESULT_VALUE_TYPE);
		mappings.put(KEY_WEIGHT_BASIS_TYPE, VALUE_WEIGHT_BASIS_TYPE);
		mappings.put(KEY_DURATION_BASIS, VALUE_DURATION_BASIS);
		mappings.put(KEY_TEMPERATURE_BASIS_LEVEL, VALUE_TEMPERATURE_BASIS_LEVEL);
		mappings.put(KEY_PARTICLE_SIZE, VALUE_PARTICLE_SIZE);
		mappings.put(KEY_PRECISION, VALUE_PRECISION);
		
		
		mappings.put(KEY_RES_MEASURE_BIAS, VALUE_RES_MEASURE_BIAS);//
		mappings.put(KEY_RES_MEASURE_CONF_INTERVAL, VALUE_RES_MEASURE_CONF_INTERVAL);//
		mappings.put(KEY_RES_MEASURE_UPPER_CONF_LIMIT, VALUE_RES_MEASURE_UPPER_CONF_LIMIT);//
		mappings.put(KEY_RES_MEASURE_LOWER_CONF_LIMIT, VALUE_RES_MEASURE_LOWER_CONF_LIMIT);//
		
		
		mappings.put(KEY_RESULT_COMMENT, VALUE_RESULT_COMMENT);
		mappings.put(KEY_P_CODE, VALUE_P_CODE);
		mappings.put(KEY_RESULT_DEPTH_MEAS_VALUE, VALUE_RESULT_DEPTH_MEAS_VALUE);
		mappings.put(KEY_RESULT_DEPTH_MEAS_UNIT_CODE, VALUE_RESULT_DEPTH_MEAS_UNIT_CODE);
		mappings.put(KEY_RESULT_DEPTH_ALT_REF_PT_TXT, VALUE_RESULT_DEPTH_ALT_REF_PT_TXT);
		
		
		mappings.put(KEY_RES_SAMPLING_POINT_NAME, VALUE_RES_SAMPLING_POINT_NAME);//
		mappings.put(KEY_BIOLOGICAL_INTENT, VALUE_BIOLOGICAL_INTENT);//
		mappings.put(KEY_RES_BIO_INDIVIDUAL_ID, VALUE_RES_BIO_INDIVIDUAL_ID);//
		
		
		mappings.put(KEY_SAMPLE_TISSUE_TAXONOMIC_NAME, VALUE_SAMPLE_TISSUE_TAXONOMIC_NAME);
		
		
		mappings.put(KEY_UNIDENTIFIEDSPECIESIDENTIFIER, VALUE_UNIDENTIFIEDSPECIESIDENTIFIER);//
		
		
		mappings.put(KEY_SAMPLE_TISSUE_ANATOMY_NAME, VALUE_SAMPLE_TISSUE_ANATOMY_NAME);
		
		
		mappings.put(KEY_RES_GROUP_SUMMARY_CT_WT, VALUE_RES_GROUP_SUMMARY_CT_WT);//
		mappings.put(KEY_RES_GROUP_SUMMARY_CT_WT_UNIT, VALUE_RES_GROUP_SUMMARY_CT_WT_UNIT);//
		mappings.put(KEY_CELL_FORM_NAME, VALUE_CELL_FORM_NAME);//
		mappings.put(KEY_CELL_SHAPE_NAME, VALUE_CELL_SHAPE_NAME);//
		mappings.put(KEY_HABIT_NAME, VALUE_HABIT_NAME);//
		mappings.put(KEY_VOLT_NAME, VALUE_VOLT_NAME);//
		mappings.put(KEY_RTDET_POLLUTION_TOLERANCE, VALUE_RTDET_POLLUTION_TOLERANCE);//
		mappings.put(KEY_RTDET_POLLUTION_TOLERNCE_SCALE, VALUE_RTDET_POLLUTION_TOLERNCE_SCALE);//
		mappings.put(KEY_RTDET_TROPHIC_LEVEL, VALUE_RTDET_TROPHIC_LEVEL);//
		mappings.put(KEY_RTFGRP_FUNCTIONAL_FEEDING_GRP, VALUE_RTFGRP_FUNCTIONAL_FEEDING_GRP);//
		mappings.put(KEY_TAXON_CITATION_TITLE, VALUE_TAXON_CITATION_TITLE);//
		mappings.put(KEY_TAXON_CITATION_CREATOR, VALUE_TAXON_CITATION_CREATOR);//
		mappings.put(KEY_TAXON_CITATION_SUBJECT, VALUE_TAXON_CITATION_SUBJECT);//
		mappings.put(KEY_TAXON_CITATION_PUBLISHER, VALUE_TAXON_CITATION_PUBLISHER);//
		mappings.put(KEY_TAXON_CITATION_DATE, VALUE_TAXON_CITATION_DATE);//
		mappings.put(KEY_TAXON_CITATION_ID, VALUE_TAXON_CITATION_ID);//
		mappings.put(KEY_FCDSC_NAME, VALUE_FCDSC_NAME);//
		mappings.put(KEY_FREQUENCY_CLASS_UNIT, VALUE_FREQUENCY_CLASS_UNIT);//
		mappings.put(KEY_FCDSC_LOWER_BOUND, VALUE_FCDSC_LOWER_BOUND);//
		mappings.put(KEY_FCDSC_UPPER_BOUND, VALUE_FCDSC_UPPER_BOUND);//
		
		
		mappings.put(KEY_ANALYTICAL_PROCEDURE_ID, VALUE_ANALYTICAL_PROCEDURE_ID);
		mappings.put(KEY_ANALYTICAL_PROCEDURE_SOURCE, VALUE_ANALYTICAL_PROCEDURE_SOURCE);
		mappings.put(KEY_ANALYTICAL_METHOD_NAME, VALUE_ANALYTICAL_METHOD_NAME);
		
		
		mappings.put(KEY_ANLMTH_QUAL_TYPE, VALUE_ANLMTH_QUAL_TYPE);//
		
		
		mappings.put(KEY_ANALYTICAL_METHOD_CITATION, VALUE_ANALYTICAL_METHOD_CITATION);
		mappings.put(KEY_LAB_NAME, VALUE_LAB_NAME);
		mappings.put(KEY_ANALYSIS_START_DATE, VALUE_ANALYSIS_START_DATE);
		
		
		mappings.put(KEY_ANALYSIS_START_TIME, VALUE_ANALYSIS_START_TIME);//
		mappings.put(KEY_ANALYSIS_START_TIMEZONE, VALUE_ANALYSIS_START_TIMEZONE);//
		mappings.put(KEY_ANALYSIS_END_DATE, VALUE_ANALYSIS_END_DATE);//
		mappings.put(KEY_ANALYSIS_END_TIME, VALUE_ANALYSIS_END_TIME);//
		mappings.put(KEY_ANALYSIS_END_TIMEZONE, VALUE_ANALYSIS_END_TIMEZONE);//
		mappings.put(KEY_RLCOM_CD, VALUE_RLCOM_CD);//
		
		
		mappings.put(KEY_LAB_REMARK, VALUE_LAB_REMARK);
		mappings.put(KEY_DETECTION_LIMIT_DESC, VALUE_DETECTION_LIMIT_DESC);
		mappings.put(KEY_DETECTION_LIMIT, VALUE_DETECTION_LIMIT);
		mappings.put(KEY_DETECTION_LIMIT_UNIT, VALUE_DETECTION_LIMIT_UNIT);
		
		
		mappings.put(KEY_RES_LAB_ACCRED_YN, VALUE_RES_LAB_ACCRED_YN);//
		mappings.put(KEY_RES_LAB_ACCRED_AUTHORITY, VALUE_RES_LAB_ACCRED_AUTHORITY);//
		mappings.put(KEY_RES_TAXONOMIST_ACCRED_YN, VALUE_RES_TAXONOMIST_ACCRED_YN);//
		mappings.put(KEY_RES_TAXONOMIST_ACCRED_AUTHORTY, VALUE_RES_TAXONOMIST_ACCRED_AUTHORTY);//
		mappings.put(KEY_PREP_METHOD_ID, VALUE_PREP_METHOD_ID);//
		mappings.put(KEY_PREP_METHOD_CONTEXT, VALUE_PREP_METHOD_CONTEXT);//
		mappings.put(KEY_PREP_METHOD_NAME, VALUE_PREP_METHOD_NAME);//
		mappings.put(KEY_PREP_METHOD_QUAL_TYPE, VALUE_PREP_METHOD_QUAL_TYPE);//
		mappings.put(KEY_PREP_METHOD_DESC, VALUE_PREP_METHOD_DESC);//
		
		
		mappings.put(KEY_ANALYSIS_PREP_DATE_TX, VALUE_ANALYSIS_PREP_DATE_TX);
		
		
		mappings.put(KEY_PREP_START_TIME, VALUE_PREP_START_TIME);//
		mappings.put(KEY_PREP_START_TIMEZONE, VALUE_PREP_START_TIMEZONE);//
		mappings.put(KEY_PREP_END_DATE, VALUE_PREP_END_DATE);//
		mappings.put(KEY_PREP_END_TIME, VALUE_PREP_END_TIME);//
		mappings.put(KEY_PREP_END_TIMEZONE, VALUE_PREP_END_TIMEZONE);//
		mappings.put(KEY_PREP_DILUTION_FACTOR, VALUE_PREP_DILUTION_FACTOR);//

		
		mappings.put(KEY_DATA_SOURCE, VALUE_DATA_SOURCE);
		
	}

}
