package gov.usgs.cida.wqp.mapping;

import java.util.LinkedHashMap;
import java.util.Map;

public class PcResultColumn extends ResultColumn {

	public static final Map<String, String> mappings;
		
	static {
		mappings = new LinkedHashMap<String,String>();
		mappings.put(KEY_ORGANIZATION, VALUE_ORGANIZATION_IDENTIFIER);
		mappings.put(KEY_ORGANIZATION_NAME, VALUE_ORGANIZATION_FORMAL_NAME);
		mappings.put(KEY_ACTIVITY, VALUE_ACTIVITY);
		mappings.put(KEY_ACTIVITY_TYPE_CODE, VALUE_ACTIVITY_TYPE_CODE);
		mappings.put(KEY_SAMPLE_MEDIA, VALUE_SAMPLE_MEDIA);
		mappings.put(KEY_ACTIVITY_MEDIA_SUBDIV_NAME, VALUE_ACTIVITY_MEDIA_SUBDIV_NAME);
		mappings.put(KEY_EVENT_DATE, VALUE_EVENT_DATE);
		mappings.put(KEY_ACTIVITY_START_TIME, VALUE_ACTIVITY_START_TIME);
		mappings.put(KEY_ACT_START_TIME_ZONE, VALUE_ACT_START_TIME_ZONE);
		mappings.put(KEY_ACTIVITY_STOP_DATE, VALUE_ACTIVITY_STOP_DATE);
		mappings.put(KEY_ACTIVITY_STOP_TIME, VALUE_ACTIVITY_STOP_TIME);
		mappings.put(KEY_ACT_STOP_TIME_ZONE, VALUE_ACT_STOP_TIME_ZONE);
		mappings.put(KEY_ACTIVITY_DEPTH, VALUE_ACTIVITY_DEPTH);
		mappings.put(KEY_ACTIVITY_DEPTH_UNIT, VALUE_ACTIVITY_DEPTH_UNIT);
		mappings.put(KEY_ACTIVITY_DEPTH_REF_POINT, VALUE_ACTIVITY_DEPTH_REF_POINT);
		mappings.put(KEY_ACTIVITY_UPPER_DEPTH, VALUE_ACTIVITY_UPPER_DEPTH);
		mappings.put(KEY_ACTIVITY_UPPER_DEPTH_UNIT, VALUE_ACTIVITY_UPPER_DEPTH_UNIT);
		mappings.put(KEY_ACTIVITY_LOWER_DEPTH, VALUE_ACTIVITY_LOWER_DEPTH);
		mappings.put(KEY_ACTIVITY_LOWER_DEPTH_UNIT, VALUE_ACTIVITY_LOWER_DEPTH_UNIT);
		mappings.put(KEY_PROJECT_ID, VALUE_PROJECT_ID);
		mappings.put(KEY_ACTIVITY_CONDUCTING_ORG, VALUE_ACTIVITY_CONDUCTING_ORG);
		mappings.put(KEY_SITE_ID, VALUE_MONITORING_LOCATION_IDENTIFIER);
		mappings.put(KEY_ACTIVITY_COMMENT, VALUE_ACTIVITY_COMMENT);
		mappings.put(KEY_SAMPLE_AQFR_NAME, VALUE_SAMPLE_AQFR_NAME);
		mappings.put(KEY_HYDROLOGIC_CONDITION_NAME, VALUE_HYDROLOGIC_CONDITION_NAME);
		mappings.put(KEY_HYDROLOGIC_EVENT_NAME, VALUE_HYDROLOGIC_EVENT_NAME);
		mappings.put(KEY_SAMPLE_COLLECT_METHOD_ID, VALUE_SAMPLE_COLLECT_METHOD_ID);
		mappings.put(KEY_SAMPLE_COLLECT_METHOD_CTX, VALUE_SAMPLE_COLLECT_METHOD_CTX);
		mappings.put(KEY_SAMPLE_COLLECT_METHOD_NAME, VALUE_SAMPLE_COLLECT_METHOD_NAME);
		mappings.put(KEY_SAMPLE_COLLECT_EQUIP_NAME, VALUE_SAMPLE_COLLECT_EQUIP_NAME);
		mappings.put(KEY_RESULT_DETECTION_CONDITION_TX, VALUE_RESULT_DETECTION_CONDITION_TX);
		mappings.put(KEY_CHARACTERISTIC_NAME, VALUE_CHARACTERISTIC_NAME);
		mappings.put(KEY_SAMPLE_FRACTION_TYPE, VALUE_SAMPLE_FRACTION_TYPE);
		mappings.put(KEY_RESULT_MEASURE_VALUE, VALUE_RESULT_MEASURE_VALUE);
		mappings.put(KEY_RESULT_UNIT, VALUE_RESULT_UNIT);
		mappings.put(KEY_RESULT_MEAS_QUAL_CODE, VALUE_RESULT_MEAS_QUAL_CODE);
		mappings.put(KEY_RESULT_VALUE_STATUS, VALUE_RESULT_VALUE_STATUS);
		mappings.put(KEY_STATISTIC_TYPE, VALUE_STATISTIC_TYPE);
		mappings.put(KEY_RESULT_VALUE_TYPE, VALUE_RESULT_VALUE_TYPE);
		mappings.put(KEY_WEIGHT_BASIS_TYPE, VALUE_WEIGHT_BASIS_TYPE);
		mappings.put(KEY_DURATION_BASIS, VALUE_DURATION_BASIS);
		mappings.put(KEY_TEMPERATURE_BASIS_LEVEL, VALUE_TEMPERATURE_BASIS_LEVEL);
		mappings.put(KEY_PARTICLE_SIZE, VALUE_PARTICLE_SIZE);
		mappings.put(KEY_PRECISION, VALUE_PRECISION);
		mappings.put(KEY_RESULT_COMMENT, VALUE_RESULT_COMMENT);
		mappings.put(KEY_P_CODE, VALUE_P_CODE);
		mappings.put(KEY_RESULT_DEPTH_MEAS_VALUE, VALUE_RESULT_DEPTH_MEAS_VALUE);
		mappings.put(KEY_RESULT_DEPTH_MEAS_UNIT_CODE, VALUE_RESULT_DEPTH_MEAS_UNIT_CODE);
		mappings.put(KEY_RESULT_DEPTH_ALT_REF_PT_TXT, VALUE_RESULT_DEPTH_ALT_REF_PT_TXT);
		mappings.put(KEY_SAMPLE_TISSUE_TAXONOMIC_NAME, VALUE_SAMPLE_TISSUE_TAXONOMIC_NAME);
		mappings.put(KEY_SAMPLE_TISSUE_ANATOMY_NAME, VALUE_SAMPLE_TISSUE_ANATOMY_NAME);
		mappings.put(KEY_ANALYTICAL_PROCEDURE_ID, VALUE_ANALYTICAL_PROCEDURE_ID);
		mappings.put(KEY_ANALYTICAL_PROCEDURE_SOURCE, VALUE_ANALYTICAL_PROCEDURE_SOURCE);
		mappings.put(KEY_ANALYTICAL_METHOD_NAME, VALUE_ANALYTICAL_METHOD_NAME);
		mappings.put(KEY_ANALYTICAL_METHOD_CITATION, VALUE_ANALYTICAL_METHOD_CITATION);
		mappings.put(KEY_LAB_NAME, VALUE_LAB_NAME);
		mappings.put(KEY_ANALYSIS_START_DATE, VALUE_ANALYSIS_START_DATE);
		mappings.put(KEY_LAB_REMARK, VALUE_LAB_REMARK);
		mappings.put(KEY_DETECTION_LIMIT_DESC, VALUE_DETECTION_LIMIT_DESC);
		mappings.put(KEY_DETECTION_LIMIT, VALUE_DETECTION_LIMIT);
		mappings.put(KEY_DETECTION_LIMIT_UNIT, VALUE_DETECTION_LIMIT_UNIT);
		mappings.put(KEY_ANALYSIS_PREP_DATE_TX, VALUE_ANALYSIS_PREP_DATE_TX);
		mappings.put(KEY_DATA_SOURCE, VALUE_DATA_SOURCE);
		
	}
	
}
