package gov.usgs.cida.wqp.mapping;

public class ProjectMonitoringLocationWeightingColumn extends BaseColumn {
	
	//ResultSet Keys
	public static final String KEY_PRJMLW_VALUE = "MEASURE_VALUE";
	public static final String KEY_PRJMLW_UNIT = "UNIT_CODE";
	public static final String KEY_PRJMLW_COMMENT = "COMMENT_TEXT";
	public static final String KEY_PRJMLW_STATISTICAL_STRATUM = "STATISTICAL_STRATUM";
	public static final String KEY_PRJMLW_LOCATION_CATEGORY = "LOCATION_CATEGORY";
	public static final String KEY_PRJMLW_LOCATION_STATUS = "LOCATION_STATUS";
	public static final String KEY_PRJMLW_REFERENCE_LOCATION_TYPE_CODE = "REFERENCE_LOCATION_TYPE_CODE";
	public static final String KEY_PRJMLW_REFERENCE_LOCATION_START_DATE = "REFERENCE_LOCATION_START_DATE";
	public static final String KEY_PRJMLW_REFERENCE_LOCATION_END_DATE = "REFERENCE_LOCATION_END_DATE";
	public static final String KEY_REFERENCE_LOCATION_CITATION_TITLE = "RESOURCE_TITLE";
	public static final String KEY_REFERENCE_LOCATION_CITATION_CREATOR = "RESOURCE_CREATOR";
	public static final String KEY_REFERENCE_LOCATION_CITATION_SUBJECT = "RESOURCE_SUBJECT";
	public static final String KEY_REFERENCE_LOCATION_CITATION_PUBLISHER = "RESOURCE_PUBLISHER";
	public static final String KEY_REFERENCE_LOCATION_CITATION_DATE = "RESOURCE_DATE ";
	public static final String KEY_REFERENCE_LOCATION_CITATION_IDENTIFIER = "RESOURCE_IDENTIFIER";
	
	//Profile Mapping of the Keys
	public static final ColumnProfile PRJMLW_VALUE = new ColumnProfile(KEY_PRJMLW_VALUE, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile PRJMLW_UNIT = new ColumnProfile(KEY_PRJMLW_UNIT, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile PRJMLW_COMMENT = new ColumnProfile(KEY_PRJMLW_COMMENT, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile PRJMLW_STATISTICAL_STRATUM = new ColumnProfile(KEY_PRJMLW_STATISTICAL_STRATUM, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile PRJMLW_LOCATION_CATEGORY = new ColumnProfile(KEY_PRJMLW_LOCATION_CATEGORY, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile PRJMLW_LOCATION_STATUS = new ColumnProfile(KEY_PRJMLW_LOCATION_STATUS, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile PRJMLW_REFERENCE_LOCATION_TYPE_CODE = new ColumnProfile(KEY_PRJMLW_REFERENCE_LOCATION_TYPE_CODE, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile PRJMLW_REFERENCE_LOCATION_START_DATE = new ColumnProfile(KEY_PRJMLW_REFERENCE_LOCATION_START_DATE, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile PRJMLW_REFERENCE_LOCATION_END_DATE = new ColumnProfile(KEY_PRJMLW_REFERENCE_LOCATION_END_DATE, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile REFERENCE_LOCATION_CITATION_TITLE = new ColumnProfile(KEY_REFERENCE_LOCATION_CITATION_TITLE, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile REFERENCE_LOCATION_CITATION_CREATOR = new ColumnProfile(KEY_REFERENCE_LOCATION_CITATION_CREATOR, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile REFERENCE_LOCATION_CITATION_SUBJECT = new ColumnProfile(KEY_REFERENCE_LOCATION_CITATION_SUBJECT, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile REFERENCE_LOCATION_CITATION_PUBLISHER = new ColumnProfile(KEY_REFERENCE_LOCATION_CITATION_PUBLISHER, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile REFERENCE_LOCATION_CITATION_DATE = new ColumnProfile(KEY_REFERENCE_LOCATION_CITATION_DATE, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	public static final ColumnProfile REFERENCE_LOCATION_CITATION_IDENTIFIER = new ColumnProfile(KEY_REFERENCE_LOCATION_CITATION_IDENTIFIER, Profile.PROJECT_MONITORING_LOCATION_WEIGHTING);
	
	private ProjectMonitoringLocationWeightingColumn() {
	}
}
