package gov.usgs.cida.wqp.mapping;

import static gov.usgs.cida.wqp.mapping.BaseWqx.*;

public class ResultColumn extends BaseColumn {

	// Result Keys
	public static final String KEY_ACTIVITY = "ACTIVITY";
	public static final String KEY_ACTIVITY_TYPE_CODE = "ACTIVITY_TYPE_CODE";
	public static final String KEY_SAMPLE_MEDIA = "SAMPLE_MEDIA";
	public static final String KEY_ACTIVITY_MEDIA_SUBDIV_NAME = "ACTIVITY_MEDIA_SUBDIV_NAME";
	public static final String KEY_EVENT_DATE = "EVENT_DATE";
	public static final String KEY_ACTIVITY_START_TIME = "ACTIVITY_START_TIME";
	public static final String KEY_ACT_START_TIME_ZONE = "ACT_START_TIME_ZONE";
	public static final String KEY_ACTIVITY_STOP_DATE = "ACTIVITY_STOP_DATE";
	public static final String KEY_ACTIVITY_STOP_TIME = "ACTIVITY_STOP_TIME";
	public static final String KEY_ACT_STOP_TIME_ZONE = "ACT_STOP_TIME_ZONE";
	public static final String KEY_ACTIVITY_RELATIVE_DEPTH = "ACTIVITY_RELATIVE_DEPTH_NAME";
	public static final String KEY_ACTIVITY_DEPTH = "ACTIVITY_DEPTH";
	public static final String KEY_ACTIVITY_DEPTH_UNIT = "ACTIVITY_DEPTH_UNIT";
	public static final String KEY_ACTIVITY_DEPTH_REF_POINT = "ACTIVITY_DEPTH_REF_POINT";
	public static final String KEY_ACTIVITY_UPPER_DEPTH = "ACTIVITY_UPPER_DEPTH";
	public static final String KEY_ACTIVITY_UPPER_DEPTH_UNIT = "ACTIVITY_UPPER_DEPTH_UNIT";
	public static final String KEY_ACTIVITY_LOWER_DEPTH = "ACTIVITY_LOWER_DEPTH";
	public static final String KEY_ACTIVITY_LOWER_DEPTH_UNIT = "ACTIVITY_LOWER_DEPTH_UNIT";
	public static final String KEY_PROJECT_ID = "PROJECT_ID";
	public static final String KEY_ACTIVITY_CONDUCTING_ORG = "ACTIVITY_CONDUCTING_ORG";
	public static final String KEY_ACTIVITY_COMMENT = "ACTIVITY_COMMENT";
	public static final String KEY_SAMPLE_AQFR_NAME = "SAMPLE_AQFR_NAME";
	public static final String KEY_HYDROLOGIC_CONDITION_NAME = "HYDROLOGIC_CONDITION_NAME";
	public static final String KEY_HYDROLOGIC_EVENT_NAME = "HYDROLOGIC_EVENT_NAME";
	public static final String KEY_ACTIVITY_LATITUDE = "ACTIVITY_LATITUDE";
	public static final String KEY_ACTIVITY_LONGITUDE = "ACTIVITY_LONGITUDE";
	public static final String KEY_ACTIVITY_SOURCE_MAP_SCALE = "ACTIVITY_SOURCE_MAP_SCALE";
	public static final String KEY_ACT_HORIZONTAL_ACCURACY = "ACT_HORIZONTAL_ACCURACY";
	public static final String KEY_ACT_HORIZONTAL_ACCURACY_UNIT = "ACT_HORIZONTAL_ACCURACY_UNIT";
	public static final String KEY_ACT_HORIZONTAL_COLLECT_METHOD = "ACT_HORIZONTAL_COLLECT_METHOD";
	public static final String KEY_ACT_HORIZONTAL_DATUM_NAME = "ACT_HORIZONTAL_DATUM_NAME";
	public static final String KEY_ASSEMBLAGE_SAMPLED_NAME = "ASSEMBLAGE_SAMPLED_NAME";
	public static final String KEY_ACT_COLLECTION_DURATION = "ACT_COLLECTION_DURATION";
	public static final String KEY_ACT_COLLECTION_DURATION_UNIT = "ACT_COLLECTION_DURATION_UNIT";
	public static final String KEY_ACT_SAM_COMPNT_NAME = "ACT_SAM_COMPNT_NAME";
	public static final String KEY_ACT_SAM_COMPNT_PLACE_IN_SERIES = "ACT_SAM_COMPNT_PLACE_IN_SERIES";
	public static final String KEY_ACT_REACH_LENGTH = "ACT_REACH_LENGTH";
	public static final String KEY_ACT_REACH_LENGTH_UNIT = "ACT_REACH_LENGTH_UNIT";
	public static final String KEY_ACT_REACH_WIDTH = "ACT_REACH_WIDTH";
	public static final String KEY_ACT_REACH_WIDTH_UNIT = "ACT_REACH_WIDTH_UNIT";
	public static final String KEY_ACT_PASS_COUNT = "ACT_PASS_COUNT";
	public static final String KEY_NET_TYPE_NAME = "NET_TYPE_NAME";
	public static final String KEY_ACT_NET_SURFACE_AREA = "ACT_NET_SURFACE_AREA";
	public static final String KEY_ACT_NET_SURFACE_AREA_UNIT = "ACT_NET_SURFACE_AREA_UNIT";
	public static final String KEY_ACT_NET_MESH_SIZE = "ACT_NET_MESH_SIZE";
	public static final String KEY_ACT_NET_MESH_SIZE_UNIT = "ACT_NET_MESH_SIZE_UNIT";
	public static final String KEY_ACT_BOAT_SPEED = "ACT_BOAT_SPEED";
	public static final String KEY_ACT_BOAT_SPEED_UNIT = "ACT_BOAT_SPEED_UNIT";
	public static final String KEY_ACT_CURRENT_SPEED = "ACT_CURRENT_SPEED";
	public static final String KEY_ACT_CURRENT_SPEED_UNIT = "ACT_CURRENT_SPEED_UNIT";
	public static final String KEY_TOXICITY_TEST_TYPE_NAME = "TOXICITY_TEST_TYPE_NAME";
	public static final String KEY_SAMPLE_COLLECT_METHOD_ID = "SAMPLE_COLLECT_METHOD_ID";
	public static final String KEY_SAMPLE_COLLECT_METHOD_CTX = "SAMPLE_COLLECT_METHOD_CTX";
	public static final String KEY_SAMPLE_COLLECT_METHOD_NAME = "SAMPLE_COLLECT_METHOD_NAME";
	public static final String KEY_ACT_SAM_COLLECT_METH_QUAL_TYPE = "ACT_SAM_COLLECT_METH_QUAL_TYPE";
	public static final String KEY_ACT_SAM_COLLECT_METH_DESC = "ACT_SAM_COLLECT_METH_DESC";
	public static final String KEY_SAMPLE_COLLECT_EQUIP_NAME = "SAMPLE_COLLECT_EQUIP_NAME";
	public static final String KEY_ACT_SAM_COLLECT_EQUIP_COMMENTS = "ACT_SAM_COLLECT_EQUIP_COMMENTS";
	public static final String KEY_ACT_SAM_PREP_METH_ID = "ACT_SAM_PREP_METH_ID";
	public static final String KEY_ACT_SAM_PREP_METH_CONTEXT = "ACT_SAM_PREP_METH_CONTEXT";
	public static final String KEY_ACT_SAM_PREP_METH_NAME = "ACT_SAM_PREP_METH_NAME";
	public static final String KEY_ACT_SAM_PREP_METH_QUAL_TYPE = "ACT_SAM_PREP_METH_QUAL_TYPE";
	public static final String KEY_ACT_SAM_PREP_METH_DESC = "ACT_SAM_PREP_METH_DESC";
	public static final String KEY_SAMPLE_CONTAINER_TYPE = "SAMPLE_CONTAINER_TYPE";
	public static final String KEY_SAMPLE_CONTAINER_COLOR = "SAMPLE_CONTAINER_COLOR";
	public static final String KEY_ACT_SAM_CHEMICAL_PRESERVATIVE = "ACT_SAM_CHEMICAL_PRESERVATIVE";
	public static final String KEY_THERMAL_PRESERVATIVE_NAME = "THERMAL_PRESERVATIVE_NAME";
	public static final String KEY_ACT_SAM_TRANSPORT_STORAGE_DESC = "ACT_SAM_TRANSPORT_STORAGE_DESC";
	public static final String KEY_METRIC_TYPE_IDENTIFIER = "METRIC_TYPE_IDENTIFIER";
	public static final String KEY_METRIC_TYPE_CONTEXT = "METRIC_TYPE_CONTEXT";
	public static final String KEY_METRIC_TYPE_NAME = "METRIC_TYPE_NAME";
	public static final String KEY_METRIC_CITATION_TITLE = "METRIC_CITATION_TITLE";
	public static final String KEY_METRIC_CITATION_CREATOR = "METRIC_CITATION_CREATOR";
	public static final String KEY_METRIC_CITATION_SUBJECT = "METRIC_CITATION_SUBJECT";
	public static final String KEY_METRIC_CITATION_PUBLISHER = "METRIC_CITATION_PUBLISHER";
	public static final String KEY_METRIC_CITATION_DATE = "METRIC_CITATION_DATE";
	public static final String KEY_METRIC_CITATION_ID = "METRIC_CITATION_ID";
	public static final String KEY_METRIC_TYPE_SCALE = "METRIC_TYPE_SCALE";
	public static final String KEY_FORMULA_DESCRIPTION = "FORMULA_DESCRIPTION";
	public static final String KEY_ACTIVITY_METRIC_VALUE = "ACTIVITY_METRIC_VALUE";
	public static final String KEY_ACTIVITY_METRIC_UNIT = "ACTIVITY_METRIC_UNIT";
	public static final String KEY_ACTIVITY_METRIC_SCORE = "ACTIVITY_METRIC_SCORE";
	public static final String KEY_ACTIVITY_METRIC_COMMENT = "ACTIVITY_METRIC_COMMENT";
	public static final String KEY_INDEX_IDENTIFIER = "INDEX_IDENTIFIER";
	public static final String KEY_RESULT_ID = "RESULT_ID";
	public static final String KEY_RES_DATA_LOGGER_LINE = "RES_DATA_LOGGER_LINE";
	public static final String KEY_RESULT_DETECTION_CONDITION_TX = "RESULT_DETECTION_CONDITION_TX";
	public static final String KEY_METHOD_SPECIFICATION_NAME = "METHOD_SPECIFICATION_NAME";
	public static final String KEY_CHARACTERISTIC_NAME = "CHARACTERISTIC_NAME";
	public static final String KEY_SAMPLE_FRACTION_TYPE = "SAMPLE_FRACTION_TYPE";
	public static final String KEY_RESULT_MEASURE_VALUE = "RESULT_MEASURE_VALUE";
	public static final String KEY_RESULT_UNIT = "RESULT_UNIT";
	public static final String KEY_RESULT_MEAS_QUAL_CODE = "RESULT_MEAS_QUAL_CODE";
	public static final String KEY_RESULT_VALUE_STATUS = "RESULT_VALUE_STATUS";
	public static final String KEY_STATISTIC_TYPE = "STATISTIC_TYPE";
	public static final String KEY_RESULT_VALUE_TYPE = "RESULT_VALUE_TYPE";
	public static final String KEY_WEIGHT_BASIS_TYPE = "WEIGHT_BASIS_TYPE";
	public static final String KEY_DURATION_BASIS = "DURATION_BASIS";
	public static final String KEY_TEMPERATURE_BASIS_LEVEL = "TEMPERATURE_BASIS_LEVEL";
	public static final String KEY_PARTICLE_SIZE = "PARTICLE_SIZE";
	public static final String KEY_PRECISION = "PRECISION";
	public static final String KEY_RES_MEASURE_BIAS = "RES_MEASURE_BIAS";
	public static final String KEY_RES_MEASURE_CONF_INTERVAL = "RES_MEASURE_CONF_INTERVAL";
	public static final String KEY_RES_MEASURE_UPPER_CONF_LIMIT = "RES_MEASURE_UPPER_CONF_LIMIT";
	public static final String KEY_RES_MEASURE_LOWER_CONF_LIMIT = "RES_MEASURE_LOWER_CONF_LIMIT";
	public static final String KEY_RESULT_COMMENT = "RESULT_COMMENT";
	public static final String KEY_P_CODE = "P_CODE";
	public static final String KEY_RESULT_DEPTH_MEAS_VALUE = "RESULT_DEPTH_MEAS_VALUE";
	public static final String KEY_RESULT_DEPTH_MEAS_UNIT_CODE = "RESULT_DEPTH_MEAS_UNIT_CODE";
	public static final String KEY_RESULT_DEPTH_ALT_REF_PT_TXT = "RESULT_DEPTH_ALT_REF_PT_TXT";
	public static final String KEY_RES_SAMPLING_POINT_NAME = "RES_SAMPLING_POINT_NAME";
	public static final String KEY_BIOLOGICAL_INTENT = "BIOLOGICAL_INTENT";
	public static final String KEY_RES_BIO_INDIVIDUAL_ID = "RES_BIO_INDIVIDUAL_ID";
	public static final String KEY_SAMPLE_TISSUE_TAXONOMIC_NAME = "SAMPLE_TISSUE_TAXONOMIC_NAME";
	public static final String KEY_UNIDENTIFIEDSPECIESIDENTIFIER = "UNIDENTIFIEDSPECIESIDENTIFIER";
	public static final String KEY_SAMPLE_TISSUE_ANATOMY_NAME = "SAMPLE_TISSUE_ANATOMY_NAME";
	public static final String KEY_RES_GROUP_SUMMARY_CT_WT = "RES_GROUP_SUMMARY_CT_WT";
	public static final String KEY_RES_GROUP_SUMMARY_CT_WT_UNIT = "RES_GROUP_SUMMARY_CT_WT_UNIT";
	public static final String KEY_CELL_FORM_NAME = "CELL_FORM_NAME";
	public static final String KEY_CELL_SHAPE_NAME = "CELL_SHAPE_NAME";
	public static final String KEY_HABIT_NAME = "HABIT_NAME";
	public static final String KEY_VOLT_NAME = "VOLT_NAME";
	public static final String KEY_RTDET_POLLUTION_TOLERANCE = "RTDET_POLLUTION_TOLERANCE";
	public static final String KEY_RTDET_POLLUTION_TOLERNCE_SCALE = "RTDET_POLLUTION_TOLERNCE_SCALE";
	public static final String KEY_RTDET_TROPHIC_LEVEL = "RTDET_TROPHIC_LEVEL";
	public static final String KEY_RTFGRP_FUNCTIONAL_FEEDING_GRP = "RTFGRP_FUNCTIONAL_FEEDING_GRP";
	public static final String KEY_TAXON_CITATION_TITLE = "TAXON_CITATION_TITLE";
	public static final String KEY_TAXON_CITATION_CREATOR = "TAXON_CITATION_CREATOR";
	public static final String KEY_TAXON_CITATION_SUBJECT = "TAXON_CITATION_SUBJECT";
	public static final String KEY_TAXON_CITATION_PUBLISHER = "TAXON_CITATION_PUBLISHER";
	public static final String KEY_TAXON_CITATION_DATE = "TAXON_CITATION_DATE";
	public static final String KEY_TAXON_CITATION_ID = "TAXON_CITATION_ID";
	public static final String KEY_FCDSC_NAME = "FCDSC_NAME";
	public static final String KEY_FREQUENCY_CLASS_UNIT = "FREQUENCY_CLASS_UNIT";
	public static final String KEY_FCDSC_LOWER_BOUND = "FCDSC_LOWER_BOUND";
	public static final String KEY_FCDSC_UPPER_BOUND = "FCDSC_UPPER_BOUND";
	public static final String KEY_ANALYTICAL_PROCEDURE_ID = "ANALYTICAL_PROCEDURE_ID";
	public static final String KEY_ANALYTICAL_PROCEDURE_SOURCE = "ANALYTICAL_PROCEDURE_SOURCE";
	public static final String KEY_ANALYTICAL_METHOD_NAME = "ANALYTICAL_METHOD_NAME";
	public static final String KEY_ANLMTH_QUAL_TYPE = "ANLMTH_QUAL_TYPE";
	public static final String KEY_ANALYTICAL_METHOD_CITATION = "ANALYTICAL_METHOD_CITATION";
	public static final String KEY_LAB_NAME = "LAB_NAME";
	public static final String KEY_ANALYSIS_START_DATE = "ANALYSIS_START_DATE";
	public static final String KEY_ANALYSIS_START_TIME = "ANALYSIS_START_TIME";
	public static final String KEY_ANALYSIS_START_TIMEZONE = "ANALYSIS_START_TIMEZONE";
	public static final String KEY_ANALYSIS_END_DATE = "ANALYSIS_END_DATE";
	public static final String KEY_ANALYSIS_END_TIME = "ANALYSIS_END_TIME";
	public static final String KEY_ANALYSIS_END_TIMEZONE = "ANALYSIS_END_TIMEZONE";
	public static final String KEY_RLCOM_CD = "RLCOM_CD";
	public static final String KEY_LAB_REMARK = "LAB_REMARK";
	public static final String KEY_DETECTION_LIMIT_DESC = "DETECTION_LIMIT_DESC";
	public static final String KEY_DETECTION_LIMIT = "DETECTION_LIMIT";
	public static final String KEY_DETECTION_LIMIT_UNIT = "DETECTION_LIMIT_UNIT";
	public static final String KEY_RES_LAB_ACCRED_YN = "RES_LAB_ACCRED_YN";
	public static final String KEY_RES_LAB_ACCRED_AUTHORITY = "RES_LAB_ACCRED_AUTHORITY";
	public static final String KEY_RES_TAXONOMIST_ACCRED_YN = "RES_TAXONOMIST_ACCRED_YN";
	public static final String KEY_RES_TAXONOMIST_ACCRED_AUTHORTY = "RES_TAXONOMIST_ACCRED_AUTHORTY";
	public static final String KEY_PREP_METHOD_ID = "PREP_METHOD_ID";
	public static final String KEY_PREP_METHOD_CONTEXT = "PREP_METHOD_CONTEXT";
	public static final String KEY_PREP_METHOD_NAME = "PREP_METHOD_NAME";
	public static final String KEY_PREP_METHOD_QUAL_TYPE = "PREP_METHOD_QUAL_TYPE";
	public static final String KEY_PREP_METHOD_DESC = "PREP_METHOD_DESC";
	public static final String KEY_ANALYSIS_PREP_DATE_TX = "ANALYSIS_PREP_DATE_TX";
	public static final String KEY_PREP_START_TIME = "PREP_START_TIME";
	public static final String KEY_PREP_START_TIMEZONE = "PREP_START_TIMEZONE";
	public static final String KEY_PREP_END_DATE = "PREP_END_DATE";
	public static final String KEY_PREP_END_TIME = "PREP_END_TIME";
	public static final String KEY_PREP_END_TIMEZONE = "PREP_END_TIMEZONE";
	public static final String KEY_PREP_DILUTION_FACTOR = "PREP_DILUTION_FACTOR";

	
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	public static final String VALUE_ACTIVITY = WQX_ACT_ID;
	public static final String VALUE_ACTIVITY_TYPE_CODE = WQX_ACT_TYPE;
	public static final String VALUE_SAMPLE_MEDIA = WQX_ACT_MEDIA;
	public static final String VALUE_ACTIVITY_MEDIA_SUBDIV_NAME = WQX_ACT_MEDIA_SUB;
	public static final String VALUE_EVENT_DATE = WQX_ACT_START_DATE;
	public static final String VALUE_ACTIVITY_START_TIME = WQX_ACT_START_TIME + VAL_DEL + WQX_TIME;
	public static final String VALUE_ACT_START_TIME_ZONE = WQX_ACT_START_TIME + VAL_DEL + WQX_TIME_ZONE;
	public static final String VALUE_ACTIVITY_STOP_DATE = WQX_ACT_END_DATE;
	public static final String VALUE_ACTIVITY_STOP_TIME = WQX_ACT_END_TIME + VAL_DEL + WQX_TIME;
	public static final String VALUE_ACT_STOP_TIME_ZONE = WQX_ACT_END_TIME + VAL_DEL + WQX_TIME_ZONE;
	public static final String VALUE_ACTIVITY_RELATIVE_DEPTH = WQX_ACT_RELATIVE_DEPTH;//
	public static final String VALUE_ACTIVITY_DEPTH = WQX_ACT_DEPTH + VAL_DEL + WQX_MEASURE_VALUE;
	public static final String VALUE_ACTIVITY_DEPTH_UNIT = WQX_ACT_DEPTH + VAL_DEL + WQX_MEASURE_UNIT;
	public static final String VALUE_ACTIVITY_DEPTH_REF_POINT = WQX_ACT_DEPTH_REFERENCE;
	public static final String VALUE_ACTIVITY_UPPER_DEPTH = WQX_ACT_TOP_DEPTH + VAL_DEL + WQX_MEASURE_VALUE;
	public static final String VALUE_ACTIVITY_UPPER_DEPTH_UNIT = WQX_ACT_TOP_DEPTH + VAL_DEL + WQX_MEASURE_UNIT;
	public static final String VALUE_ACTIVITY_LOWER_DEPTH = WQX_ACT_BOTTOM_DEPTH + VAL_DEL + WQX_MEASURE_VALUE;
	public static final String VALUE_ACTIVITY_LOWER_DEPTH_UNIT = WQX_ACT_BOTTOM_DEPTH + VAL_DEL + WQX_MEASURE_UNIT;
	public static final String VALUE_PROJECT_ID = WQX_PROJECT;
	public static final String VALUE_ACTIVITY_CONDUCTING_ORG = WQX_ACT_CONDUCTION_ORG;
	public static final String VALUE_ACTIVITY_COMMENT = WQX_ACT_COMMENT;
	public static final String VALUE_SAMPLE_AQFR_NAME = WQX_SAMPLE_AQUIFER;
	public static final String VALUE_HYDROLOGIC_CONDITION_NAME = WQX_HYDROLOGIC_CONDITION;
	public static final String VALUE_HYDROLOGIC_EVENT_NAME = WQX_HYDROLOGIC_EVENT;
	public static final String VALUE_ACTIVITY_LATITUDE = WQX_ACT_LOCATION + VAL_DEL + WQX_LATITUDE_MEASURE;//
	public static final String VALUE_ACTIVITY_LONGITUDE = WQX_ACT_LOCATION + VAL_DEL + WQX_LONGITUDE_MEASURE;//
	public static final String VALUE_ACTIVITY_SOURCE_MAP_SCALE = WQX_ACT_LOCATION + VAL_DEL + WQX_SOURCE_MAP_SCALE;//
	public static final String VALUE_ACT_HORIZONTAL_ACCURACY = WQX_ACT_LOCATION + VAL_DEL + WQX_HORIZONTAL_ACCY + VAL_DEL + WQX_MEASURE_VALUE;//
	public static final String VALUE_ACT_HORIZONTAL_ACCURACY_UNIT = WQX_ACT_LOCATION + VAL_DEL + WQX_HORIZONTAL_ACCY + VAL_DEL + WQX_MEASURE_UNIT;//
	public static final String VALUE_ACT_HORIZONTAL_COLLECT_METHOD = WQX_ACT_LOCATION + VAL_DEL + WQX_HORIZONTAL_COLLECTION_METHOD;//
	public static final String VALUE_ACT_HORIZONTAL_DATUM_NAME = WQX_ACT_LOCATION + VAL_DEL + WQX_HORIZONTAL_DATUM;//
	public static final String VALUE_ASSEMBLAGE_SAMPLED_NAME = WQX_ASSEMBLAGE_SAMPLED;//
	public static final String VALUE_ACT_COLLECTION_DURATION = WQX_COLLECTION_DURATION + VAL_DEL + WQX_MEASURE_VALUE;//
	public static final String VALUE_ACT_COLLECTION_DURATION_UNIT = WQX_COLLECTION_DURATION + VAL_DEL + WQX_MEASURE_UNIT;//
	public static final String VALUE_ACT_SAM_COMPNT_NAME = WQX_SAMPLING_COMPONENT;//
	public static final String VALUE_ACT_SAM_COMPNT_PLACE_IN_SERIES = WQX_SAMPLING_COMPONENT_PLACE;//
	public static final String VALUE_ACT_REACH_LENGTH = WQX_REACH_LENGTH + VAL_DEL + WQX_MEASURE_VALUE;//
	public static final String VALUE_ACT_REACH_LENGTH_UNIT = WQX_REACH_LENGTH + VAL_DEL + WQX_MEASURE_UNIT;//
	public static final String VALUE_ACT_REACH_WIDTH = WQX_REACH_WIDTH + VAL_DEL + WQX_MEASURE_VALUE;//
	public static final String VALUE_ACT_REACH_WIDTH_UNIT = WQX_REACH_WIDTH + VAL_DEL + WQX_MEASURE_UNIT;//
	public static final String VALUE_ACT_PASS_COUNT = WQX_PASS_COUNT;//
	public static final String VALUE_NET_TYPE_NAME = WQX_NET_TYPE;//
	public static final String VALUE_ACT_NET_SURFACE_AREA = WQX_NET_SURFACE_AREA + VAL_DEL + WQX_MEASURE_VALUE;//
	public static final String VALUE_ACT_NET_SURFACE_AREA_UNIT = WQX_NET_SURFACE_AREA + VAL_DEL + WQX_MEASURE_UNIT;//
	public static final String VALUE_ACT_NET_MESH_SIZE = WQX_NET_MESH_SIZE + VAL_DEL + WQX_MEASURE_VALUE;//
	public static final String VALUE_ACT_NET_MESH_SIZE_UNIT = WQX_NET_MESH_SIZE + VAL_DEL + WQX_MEASURE_UNIT;//
	public static final String VALUE_ACT_BOAT_SPEED = WQX_BOAT_SPEAD + VAL_DEL + WQX_MEASURE_VALUE;//
	public static final String VALUE_ACT_BOAT_SPEED_UNIT = WQX_BOAT_SPEAD + VAL_DEL + WQX_MEASURE_UNIT;//
	public static final String VALUE_ACT_CURRENT_SPEED = WQX_CURRENT_SPEAD + VAL_DEL + WQX_MEASURE_VALUE;//
	public static final String VALUE_ACT_CURRENT_SPEED_UNIT = WQX_CURRENT_SPEAD + VAL_DEL + WQX_MEASURE_UNIT;//
	public static final String VALUE_TOXICITY_TEST_TYPE_NAME = WQX_TOXICITY_TEST_TYPE;//

	
	public static final String VALUE_SAMPLE_COLLECT_METHOD_ID = WQX_COLLECTION_METHOD + VAL_DEL + WQX_METHOD_ID;
	public static final String VALUE_SAMPLE_COLLECT_METHOD_CTX = WQX_COLLECTION_METHOD + VAL_DEL + WQX_METHOD_CONTEXT;
	public static final String VALUE_SAMPLE_COLLECT_METHOD_NAME = WQX_COLLECTION_METHOD + VAL_DEL + WQX_METHOD_NAME;
	
	
	public static final String VALUE_ACT_SAM_COLLECT_METH_QUAL_TYPE = WQX_COLLECTION_METHOD + VAL_DEL + WQX_METHOD_QUALIFIER_TYPE;//
	public static final String VALUE_ACT_SAM_COLLECT_METH_DESC = WQX_COLLECTION_METHOD + VAL_DEL + WQX_METHOD_DESCRIPTION;//
	
	
	public static final String VALUE_SAMPLE_COLLECT_EQUIP_NAME = WQX_COLLECTION_EQUIPMENT;
	
	
	public static final String VALUE_ACT_SAM_COLLECT_EQUIP_COMMENTS = WQX_COLLECTION_METHOD + VAL_DEL + WQX_COLLECTION_EQUIPMENT_COMMENT;//
	public static final String VALUE_ACT_SAM_PREP_METH_ID = WQX_SAMPLE_PREPARATION_METHOD + VAL_DEL + WQX_METHOD_ID;//
	public static final String VALUE_ACT_SAM_PREP_METH_CONTEXT = WQX_SAMPLE_PREPARATION_METHOD + VAL_DEL + WQX_METHOD_CONTEXT;//
	public static final String VALUE_ACT_SAM_PREP_METH_NAME = WQX_SAMPLE_PREPARATION_METHOD + VAL_DEL + WQX_METHOD_NAME;//
	public static final String VALUE_ACT_SAM_PREP_METH_QUAL_TYPE = WQX_SAMPLE_PREPARATION_METHOD + VAL_DEL + WQX_METHOD_QUALIFIER_TYPE;//
	public static final String VALUE_ACT_SAM_PREP_METH_DESC = WQX_SAMPLE_PREPARATION_METHOD + VAL_DEL + WQX_METHOD_DESCRIPTION;//
	public static final String VALUE_SAMPLE_CONTAINER_TYPE = WQX_SAMPLE_CONTAINER_TYPE;//
	public static final String VALUE_SAMPLE_CONTAINER_COLOR = WQX_SAMPLE_CONTAINER_COLOR;//
	public static final String VALUE_ACT_SAM_CHEMICAL_PRESERVATIVE = WQX_CHEMICAL_PRESERVATIVE;//
	public static final String VALUE_THERMAL_PRESERVATIVE_NAME = WQX_THERMAL_PRESERVATIVE;//
	public static final String VALUE_ACT_SAM_TRANSPORT_STORAGE_DESC = WQX_TRANSPORT_STORAGE;//
	public static final String VALUE_METRIC_TYPE_IDENTIFIER = WQX_METRIC_TYPE_ID;//
	public static final String VALUE_METRIC_TYPE_CONTEXT = WQX_METRIC_TYPE_ID_CONTEXT;//
	public static final String VALUE_METRIC_TYPE_NAME = WQX_METRIC_TYPE;//
	public static final String VALUE_METRIC_CITATION_TITLE = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_RESOURCE_TITLE;//
	public static final String VALUE_METRIC_CITATION_CREATOR = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_RESOURCE_CREATOR;//
	public static final String VALUE_METRIC_CITATION_SUBJECT = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_RESOURCE_SUBJECT;//
	public static final String VALUE_METRIC_CITATION_PUBLISHER = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_RESOURCE_PUBLISHER;//
	public static final String VALUE_METRIC_CITATION_DATE = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_RESOURCE_DATE;//
	public static final String VALUE_METRIC_CITATION_ID = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_RESOURCE_ID;//
	public static final String VALUE_METRIC_TYPE_SCALE = WQX_METRIC_TYPE_SCALE;//
	public static final String VALUE_FORMULA_DESCRIPTION = WQX_FORMULA_DESCRIPTION;//
	public static final String VALUE_ACTIVITY_METRIC_VALUE = WQX_METRIC_VALUE + VAL_DEL + WQX_MEASURE_VALUE;//
	public static final String VALUE_ACTIVITY_METRIC_UNIT = WQX_METRIC_VALUE + VAL_DEL + WQX_MEASURE_UNIT;//
	public static final String VALUE_ACTIVITY_METRIC_SCORE = WQX_METRIC_SCORE;//
	public static final String VALUE_ACTIVITY_METRIC_COMMENT = WQX_METRIC_COMMENT;//
	public static final String VALUE_INDEX_IDENTIFIER = WQX_INDEX_ID;//
	public static final String VALUE_RES_DATA_LOGGER_LINE = WQX_DATA_LOGGER_LINE;//

	
	public static final String VALUE_RESULT_DETECTION_CONDITION_TX = WQX_DETECTION_CONDITION;
	
	
	public static final String VALUE_METHOD_SPECIFICATION_NAME = WQX_METHOD_SPECIFICATION;//
	
	
	public static final String VALUE_CHARACTERISTIC_NAME = WQX_CHAR_NAME;
	public static final String VALUE_SAMPLE_FRACTION_TYPE = WQX_SAMPLE_FRACTION;
	public static final String VALUE_RESULT_MEASURE_VALUE = WQX_RESULT_MEASURE_VALUE;
	public static final String VALUE_RESULT_UNIT = WQX_RESULT_MEASURE + VAL_DEL + WQX_MEASURE_UNIT;
	public static final String VALUE_RESULT_MEAS_QUAL_CODE = WQX_MEASURE_QUALIFIER;
	public static final String VALUE_RESULT_VALUE_STATUS = WQX_STATUS_ID;
	public static final String VALUE_STATISTIC_TYPE = WQX_STATISTICAL_BASE;
	public static final String VALUE_RESULT_VALUE_TYPE = WQX_VALUE_TYPE;
	public static final String VALUE_WEIGHT_BASIS_TYPE = WQX_WEIGHT_BASIS;
	public static final String VALUE_DURATION_BASIS = WQX_TIME_BASIS;
	public static final String VALUE_TEMPERATURE_BASIS_LEVEL = WQX_TEMP_BASIS;
	public static final String VALUE_PARTICLE_SIZE = WQX_PARTICLE_SIZE;
	public static final String VALUE_PRECISION = WQX_PRECISION;
	
	
	public static final String VALUE_RES_MEASURE_BIAS = WQX_DATA_QUALITY + VAL_DEL + WQX_BIAS;//
	public static final String VALUE_RES_MEASURE_CONF_INTERVAL = WQX_CONFIDENCE_INTERVAL;//
	public static final String VALUE_RES_MEASURE_UPPER_CONF_LIMIT = WQX_UPPER_CONFIDENCE_LIMIT;//
	public static final String VALUE_RES_MEASURE_LOWER_CONF_LIMIT = WQX_LOWER_CONFIDENCE_LIMIT;//
	
	
	public static final String VALUE_RESULT_COMMENT = WQX_RESULT_COMMENT;
	public static final String VALUE_P_CODE = WQX_P_CODE;
	public static final String VALUE_RESULT_DEPTH_MEAS_VALUE = WQX_RESULT_DEPTH + VAL_DEL + WQX_MEASURE_VALUE;
	public static final String VALUE_RESULT_DEPTH_MEAS_UNIT_CODE = WQX_RESULT_DEPTH + VAL_DEL + WQX_MEASURE_UNIT;
	public static final String VALUE_RESULT_DEPTH_ALT_REF_PT_TXT = WQX_RESULT_DETH_REFERENCE;
	
	
	public static final String VALUE_RES_SAMPLING_POINT_NAME = WQX_RESULT_SAMPLING_POINT;//
	public static final String VALUE_BIOLOGICAL_INTENT = WQX_BIOLOGICAL_INTENT;//
	public static final String VALUE_RES_BIO_INDIVIDUAL_ID = WQX_BIOLOGICAL_INDIVIDUAL_ID;//
	
	
	public static final String VALUE_SAMPLE_TISSUE_TAXONOMIC_NAME = WQX_TAXON_NAME;
	
	
	public static final String VALUE_UNIDENTIFIEDSPECIESIDENTIFIER = WQX_UNIDENTIFIED_SPECIES_IDENTIFIER;//
	
	
	public static final String VALUE_SAMPLE_TISSUE_ANATOMY_NAME = WQX_TISSUE_ANATOMY;
	
	
	public static final String VALUE_RES_GROUP_SUMMARY_CT_WT = WQX_GROUP_SUMMARY_COUNT_WEIGHT + VAL_DEL + WQX_MEASURE_VALUE;//
	public static final String VALUE_RES_GROUP_SUMMARY_CT_WT_UNIT = WQX_GROUP_SUMMARY_COUNT_WEIGHT + VAL_DEL + WQX_MEASURE_UNIT;//
	public static final String VALUE_CELL_FORM_NAME = WQX_CELL_FORM;//
	public static final String VALUE_CELL_SHAPE_NAME = WQX_CELL_SHAPE;//
	public static final String VALUE_HABIT_NAME = WQX_HABIT;//
	public static final String VALUE_VOLT_NAME = WQX_VOLTISM;//
	public static final String VALUE_RTDET_POLLUTION_TOLERANCE = WQX_POLLUTION_TOLERANCE;//
	public static final String VALUE_RTDET_POLLUTION_TOLERNCE_SCALE = WQX_TOLERANCE_SCALE;//
	public static final String VALUE_RTDET_TROPHIC_LEVEL = WQX_TROPHIC_LEVEL;//
	public static final String VALUE_RTFGRP_FUNCTIONAL_FEEDING_GRP = WQX_FUNCTIONAL_FEEDING_GROUP;//
	public static final String VALUE_TAXON_CITATION_TITLE = WQX_TAXONIMC_DETAIL_CITATION + VAL_DEL + WQX_RESOURCE_TITLE;//
	public static final String VALUE_TAXON_CITATION_CREATOR = WQX_TAXONIMC_DETAIL_CITATION + VAL_DEL + WQX_RESOURCE_CREATOR;//
	public static final String VALUE_TAXON_CITATION_SUBJECT = WQX_TAXONIMC_DETAIL_CITATION + VAL_DEL + WQX_RESOURCE_SUBJECT;//
	public static final String VALUE_TAXON_CITATION_PUBLISHER = WQX_TAXONIMC_DETAIL_CITATION + VAL_DEL + WQX_RESOURCE_PUBLISHER;//
	public static final String VALUE_TAXON_CITATION_DATE = WQX_TAXONIMC_DETAIL_CITATION + VAL_DEL + WQX_RESOURCE_DATE;//
	public static final String VALUE_TAXON_CITATION_ID = WQX_TAXONIMC_DETAIL_CITATION + VAL_DEL + WQX_RESOURCE_ID;//
	public static final String VALUE_FCDSC_NAME = WQX_FREQUENCY_CLASS_DESCRIPTOR;//
	public static final String VALUE_FREQUENCY_CLASS_UNIT = WQX_FREQUENCE_CLASS_DESCRIPTOR_UNIT;//
	public static final String VALUE_FCDSC_LOWER_BOUND = WQX_LOWER_CLASS_BOUND;//
	public static final String VALUE_FCDSC_UPPER_BOUND = WQX_UPPER_CLASS_BOUND;//
	
	
	public static final String VALUE_ANALYTICAL_PROCEDURE_ID = WQX_ANALYTICAL_METHOD + VAL_DEL + WQX_METHOD_ID;
	public static final String VALUE_ANALYTICAL_PROCEDURE_SOURCE = WQX_ANALYTICAL_METHOD + VAL_DEL + WQX_METHOD_CONTEXT;
	public static final String VALUE_ANALYTICAL_METHOD_NAME = WQX_ANALYTICAL_METHOD + VAL_DEL + WQX_METHOD_NAME;
	
	
	public static final String VALUE_ANLMTH_QUAL_TYPE = WQX_ANALYTICAL_METHOD + VAL_DEL + WQX_METHOD_QUALIFIER_TYPE;//
	
	
	public static final String VALUE_ANALYTICAL_METHOD_CITATION = WQX_METHOD_DESCRIPTION;
	public static final String VALUE_LAB_NAME = WQX_LAB_NAME;
	public static final String VALUE_ANALYSIS_START_DATE = WQX_ANALYSIS_START_DATE;
	
	
	public static final String VALUE_ANALYSIS_START_TIME = WQX_ANALYSIS_START_TIME + VAL_DEL + WQX_TIME;//
	public static final String VALUE_ANALYSIS_START_TIMEZONE = WQX_ANALYSIS_START_TIME + VAL_DEL + WQX_TIME_ZONE;//
	public static final String VALUE_ANALYSIS_END_DATE = WQX_ANALYSIS_END_DATE;//
	public static final String VALUE_ANALYSIS_END_TIME = WQX_ANALYSIS_END_TIME + VAL_DEL + WQX_TIME;//
	public static final String VALUE_ANALYSIS_END_TIMEZONE = WQX_ANALYSIS_END_TIME + VAL_DEL + WQX_TIME_ZONE;//
	public static final String VALUE_RLCOM_CD = WQX_LAB_COMMENT_CODE;//
	
	
	public static final String VALUE_LAB_REMARK = WQX_LAB_COMMENT;
	public static final String VALUE_DETECTION_LIMIT_DESC = WQX_DETECTION_LIMIT_TYPE;
	public static final String VALUE_DETECTION_LIMIT = WQX_DETECTION_LIMIT_VALUE + VAL_DEL + WQX_MEASURE_VALUE;
	public static final String VALUE_DETECTION_LIMIT_UNIT = WQX_DETECTION_LIMIT_VALUE + VAL_DEL + WQX_MEASURE_UNIT;
	
	
	public static final String VALUE_RES_LAB_ACCRED_YN = WQX_LAB_ACCREDITATION_INDICATOR;//
	public static final String VALUE_RES_LAB_ACCRED_AUTHORITY = WQX_LAB_ACCREDITATION_AUTHORITY;//
	public static final String VALUE_RES_TAXONOMIST_ACCRED_YN = WQX_TAXONOMIST_ACCREDITATION_INDICATOR;//
	public static final String VALUE_RES_TAXONOMIST_ACCRED_AUTHORTY = WQX_TAXONOMIST_ACCREDITATION_AUTHORTY;//
	public static final String VALUE_PREP_METHOD_ID = WQX_LAB_SAMPLE_PREP_METHOD + VAL_DEL + WQX_METHOD_ID;//
	public static final String VALUE_PREP_METHOD_CONTEXT = WQX_LAB_SAMPLE_PREP_METHOD + VAL_DEL + WQX_METHOD_CONTEXT;//
	public static final String VALUE_PREP_METHOD_NAME = WQX_LAB_SAMPLE_PREP_METHOD + VAL_DEL + WQX_METHOD_NAME;//
	public static final String VALUE_PREP_METHOD_QUAL_TYPE = WQX_LAB_SAMPLE_PREP_METHOD + VAL_DEL + WQX_METHOD_QUALIFIER_TYPE;//
	public static final String VALUE_PREP_METHOD_DESC = WQX_LAB_SAMPLE_PREP_METHOD + VAL_DEL + WQX_METHOD_DESCRIPTION;//
	
	
	public static final String VALUE_ANALYSIS_PREP_DATE_TX = WQX_PREP_START_DATE;
	
	
	public static final String VALUE_PREP_START_TIME = WQX_PREP_START_TIME + VAL_DEL + WQX_TIME;//
	public static final String VALUE_PREP_START_TIMEZONE = WQX_PREP_START_TIME + VAL_DEL + WQX_TIME_ZONE;//
	public static final String VALUE_PREP_END_DATE = WQX_PREP_END_DATE;//
	public static final String VALUE_PREP_END_TIME = WQX_PREP_END_TIME + VAL_DEL + WQX_TIME;//
	public static final String VALUE_PREP_END_TIMEZONE = WQX_PREP_END_TIME + VAL_DEL + WQX_TIME_ZONE;//
	public static final String VALUE_PREP_DILUTION_FACTOR = WQX_SUBSTITUTION_DILUTION_FACTOR;//

	

}
