package gov.usgs.wma.wqp.mapping.delimited;

import static gov.usgs.wma.wqp.mapping.ActivityColumn.*;
import static gov.usgs.wma.wqp.mapping.ActivityMetricColumn.*;
import static gov.usgs.wma.wqp.mapping.delimited.ActivityDelimited.*;
import static gov.usgs.wma.wqp.mapping.xml.BaseWqx.*;

import java.util.LinkedHashMap;
import java.util.Map;

import gov.usgs.wma.wqp.mapping.ColumnProfile;
import gov.usgs.wma.wqp.mapping.Profile;

public class ActivityMetricDelimited extends BaseDelimited {

	//Column Headings for the Keys
	public static final String VALUE_METRIC_TYPE_IDENTIFIER = WQX_ACTIVITY_METRIC_TYPE + VAL_DEL + WQX_METRIC_TYPE_ID;
	public static final String VALUE_METRIC_TYPE_CONTEXT = WQX_ACTIVITY_METRIC_TYPE + VAL_DEL + WQX_METRIC_TYPE_ID_CONTEXT;
	public static final String VALUE_METRIC_TYPE_NAME = WQX_ACTIVITY_METRIC_TYPE + VAL_DEL + WQX_METRIC_TYPE;
	public static final String VALUE_METRIC_CITATION_TITLE = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_RESOURCE_TITLE;
	public static final String VALUE_METRIC_CITATION_CREATOR = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_RESOURCE_CREATOR;
	public static final String VALUE_METRIC_CITATION_SUBJECT = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_RESOURCE_SUBJECT;
	public static final String VALUE_METRIC_CITATION_PUBLISHER = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_RESOURCE_PUBLISHER;
	public static final String VALUE_METRIC_CITATION_DATE = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_RESOURCE_DATE;
	public static final String VALUE_METRIC_CITATION_ID = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_RESOURCE_ID;
	public static final String VALUE_METRIC_TYPE_SCALE = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_METRIC_TYPE_SCALE;
	public static final String VALUE_FORMULA_DESCRIPTION = WQX_METRIC_TYPE_CITATION + VAL_DEL + WQX_FORMULA_DESCRIPTION;
	public static final String VALUE_ACTIVITY_METRIC_VALUE = WQX_METRIC_VALUE + VAL_DEL + WQX_MEASURE_VALUE;
	public static final String VALUE_ACTIVITY_METRIC_UNIT = WQX_METRIC_VALUE + VAL_DEL + WQX_MEASURE_UNIT;
	public static final String VALUE_ACTIVITY_METRIC_SCORE = WQX_METRIC_VALUE + VAL_DEL + WQX_METRIC_SCORE;
	public static final String VALUE_ACTIVITY_METRIC_COMMENT = WQX_METRIC_VALUE + VAL_DEL + WQX_METRIC_COMMENT;
	public static final String VALUE_INDEX_IDENTIFIER = WQX_METRIC_VALUE + VAL_DEL + WQX_INDEX_ID;

	public static final Map<ColumnProfile, String> MAPPINGS;

	static {
		MAPPINGS = new LinkedHashMap<ColumnProfile,String>();
		MAPPINGS.put(ORGANIZATION, VALUE_ORGANIZATION_IDENTIFIER);
		MAPPINGS.put(ORGANIZATION_NAME, VALUE_ORGANIZATION_FORMAL_NAME);
		MAPPINGS.put(SITE_ID, VALUE_MONITORING_LOCATION_IDENTIFIER);
		MAPPINGS.put(ACTIVITY, VALUE_ACTIVITY);

		MAPPINGS.put(METRIC_TYPE_IDENTIFIER, VALUE_METRIC_TYPE_IDENTIFIER);
		MAPPINGS.put(METRIC_TYPE_CONTEXT, VALUE_METRIC_TYPE_CONTEXT);
		MAPPINGS.put(METRIC_TYPE_NAME, VALUE_METRIC_TYPE_NAME);
		MAPPINGS.put(METRIC_CITATION_TITLE, VALUE_METRIC_CITATION_TITLE);
		MAPPINGS.put(METRIC_CITATION_CREATOR, VALUE_METRIC_CITATION_CREATOR);
		MAPPINGS.put(METRIC_CITATION_SUBJECT, VALUE_METRIC_CITATION_SUBJECT);
		MAPPINGS.put(METRIC_CITATION_PUBLISHER, VALUE_METRIC_CITATION_PUBLISHER);
		MAPPINGS.put(METRIC_CITATION_DATE, VALUE_METRIC_CITATION_DATE);
		MAPPINGS.put(METRIC_CITATION_ID, VALUE_METRIC_CITATION_ID);
		MAPPINGS.put(METRIC_TYPE_SCALE, VALUE_METRIC_TYPE_SCALE);
		MAPPINGS.put(FORMULA_DESCRIPTION, VALUE_FORMULA_DESCRIPTION);
		MAPPINGS.put(ACTIVITY_METRIC_VALUE, VALUE_ACTIVITY_METRIC_VALUE);
		MAPPINGS.put(ACTIVITY_METRIC_UNIT, VALUE_ACTIVITY_METRIC_UNIT);
		MAPPINGS.put(ACTIVITY_METRIC_SCORE, VALUE_ACTIVITY_METRIC_SCORE);
		MAPPINGS.put(ACTIVITY_METRIC_COMMENT, VALUE_ACTIVITY_METRIC_COMMENT);
		MAPPINGS.put(INDEX_IDENTIFIER, VALUE_INDEX_IDENTIFIER);

		MAPPINGS.put(DATA_SOURCE, VALUE_DATA_SOURCE);
	}

	private ActivityMetricDelimited() {
	}

	public static Map<String, String> getMapping(Profile profile) {
		return getMapping(MAPPINGS, profile);
	}

}
