package gov.usgs.cida.wqp.mapping.xml;

public class ActivityMetricWqx {

	
//	COLUMN_POSITION.put(KEY_METRIC_TYPE_IDENTIFIER,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_ACTIVITY_METRIC_TYPE,
//					WQX_METRIC_TYPE_ID)));
//	COLUMN_POSITION.put(KEY_METRIC_TYPE_CONTEXT,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_ACTIVITY_METRIC_TYPE,
//					WQX_METRIC_TYPE_ID_CONTEXT)));
//	COLUMN_POSITION.put(KEY_METRIC_TYPE_NAME,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_ACTIVITY_METRIC_TYPE,
//					WQX_METRIC_TYPE)));
//	COLUMN_POSITION.put(KEY_METRIC_CITATION_TITLE,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_ACTIVITY_METRIC_TYPE,
//					WQX_METRIC_TYPE_CITATION,
//					WQX_RESOURCE_TITLE)));
//	COLUMN_POSITION.put(KEY_METRIC_CITATION_CREATOR,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_ACTIVITY_METRIC_TYPE,
//					WQX_METRIC_TYPE_CITATION,
//					WQX_RESOURCE_CREATOR)));
//	COLUMN_POSITION.put(KEY_METRIC_CITATION_SUBJECT,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_ACTIVITY_METRIC_TYPE,
//					WQX_METRIC_TYPE_CITATION,
//					WQX_RESOURCE_SUBJECT)));
//	COLUMN_POSITION.put(KEY_METRIC_CITATION_PUBLISHER,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_ACTIVITY_METRIC_TYPE,
//					WQX_METRIC_TYPE_CITATION,
//					WQX_RESOURCE_PUBLISHER)));
//	COLUMN_POSITION.put(KEY_METRIC_CITATION_DATE,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_ACTIVITY_METRIC_TYPE,
//					WQX_METRIC_TYPE_CITATION,
//					WQX_RESOURCE_DATE)));
//	COLUMN_POSITION.put(KEY_METRIC_CITATION_ID,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_ACTIVITY_METRIC_TYPE,
//					WQX_METRIC_TYPE_CITATION,
//					WQX_RESOURCE_ID)));
//	COLUMN_POSITION.put(KEY_METRIC_TYPE_SCALE,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_ACTIVITY_METRIC_TYPE,
//					WQX_METRIC_TYPE_SCALE)));
//	COLUMN_POSITION.put(KEY_FORMULA_DESCRIPTION,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_ACTIVITY_METRIC_TYPE,
//					WQX_FORMULA_DESCRIPTION)));
//	COLUMN_POSITION.put(KEY_ACTIVITY_METRIC_VALUE,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_METRIC_VALUE,
//					WQX_MEASURE_VALUE)));
//	COLUMN_POSITION.put(KEY_ACTIVITY_METRIC_UNIT,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_METRIC_VALUE,
//					WQX_MEASURE_UNIT)));
//	COLUMN_POSITION.put(KEY_ACTIVITY_METRIC_SCORE,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_METRIC_SCORE)));
//	COLUMN_POSITION.put(KEY_ACTIVITY_METRIC_COMMENT,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_METRIC_COMMENT)));
//	COLUMN_POSITION.put(KEY_INDEX_IDENTIFIER,
//			new LinkedList<String>(Arrays.asList(
//					WQX_ACTIVITY,
//					WQX_ACTIVITY_METRIC,
//					WQX_INDEX_ID)));

}
