package gov.usgs.wma.wqp.openapi.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import gov.usgs.wma.wqp.util.HttpConstants;

public class ProjectMonitoringLocationWeightingCountJson {
	
	public static final String HEADER_NWIS_PROJECT_MONITORING_LOCATION_WEIGHTING_COUNT = StationCountJson.NWIS + HttpConstants.HEADER_DELIMITER + HttpConstants.HEADER_PROJECT_MONITORING_LOCATION_WEIGHTING_COUNT;
	public static final String HEADER_STEWARDS_PROJECT_MONITORING_LOCATION_WEIGHTING_COUNT = StationCountJson.STEWARDS + HttpConstants.HEADER_DELIMITER + HttpConstants.HEADER_PROJECT_MONITORING_LOCATION_WEIGHTING_COUNT;
	public static final String HEADER_STORET_PROJECT_MONITORING_LOCATION_WEIGHTING_COUNT = StationCountJson.STORET + HttpConstants.HEADER_DELIMITER + HttpConstants.HEADER_PROJECT_MONITORING_LOCATION_WEIGHTING_COUNT;
	public static final String HEADER_BIODATA_PROJECT_MONITORING_LOCATION_WEIGHTING_COUNT = StationCountJson.BIODATA + HttpConstants.HEADER_DELIMITER + HttpConstants.HEADER_PROJECT_MONITORING_LOCATION_WEIGHTING_COUNT;
	
	@JsonProperty(HttpConstants.HEADER_TOTAL_PROJECT_MONITORING_LOCATION_WEIGHTING_COUNT)
	String totalProjectCount;
	@JsonProperty(HEADER_NWIS_PROJECT_MONITORING_LOCATION_WEIGHTING_COUNT)
	String nwisProjectCount;
	@JsonProperty(HEADER_STEWARDS_PROJECT_MONITORING_LOCATION_WEIGHTING_COUNT)
	String stewardsProjectCount;
	@JsonProperty(HEADER_STORET_PROJECT_MONITORING_LOCATION_WEIGHTING_COUNT)
	String storetProjectCount;
	@JsonProperty(HEADER_BIODATA_PROJECT_MONITORING_LOCATION_WEIGHTING_COUNT)
	String biodataProjectCount;
	
}
